### ISSUE TITLE
Get all the objects, references and attributes of a model

### ISSUE THREAD

**Issue by Z-Rajaei** [pyecore/pyecore#102]
Hello,
I am trying to get all the objects (classes), references and attributes in a model. Nothing is known in advance (including the name of the objects and the attributes, because the metamodel and model may vary in different situations, and I want to have a general code to extract the elements from an xmi file).

I loaded my ecore and xmi files, But I do not know how to access the objects and their attributes, because I do not know what the class name is for example.

from pyecore.resources import ResourceSet, URI
rset = ResourceSet()
resource = rset.get_resource(URI('a.ecore'))
mm_root = resource.contents[0]

rset.metamodel_registry[mm_root.nsURI] = mm_root
resource = rset.get_resource(URI('m.xmi'))
model_root = resource.contents[0]

Thanks!

**Comment by aranega** [comment]
Hi @Z-Rajaei,

Sorry for the late answer...

Gathering all the references/attributes of a model is not a problem thanks to the reflection layer. Basically, the idea is to take an object, get its metaclass, then iterate over all the features of the metaclass and ask the instance which values are associated to it. There is various way of doing it in PyEcore, here is one:

```python
for x in (model_root, *model_root.eAllContents()): # Ask for all the children of a root
    eclass = x.eClass   # Get the metaclass
    for feature in eclass.eAllStructuralFeatures(): # iterate over all features
        if feature.many:
            print(f"The value of feature {feature.name} of {x.eClass.name} is a collection")
        else:
            print(f"The value of feature {feature.name} of {x.eClass.name} is a single value")
        print(f"Value for {feature.name} of {x} => {x.eGet(feature)}")

```

Hope this helps

**Comment by Z-Rajaei** [comment]
Hi @aranega 
Thank you. It was very helpful.
