### ISSUE TITLE
eAnnotations for EObjects?

### ISSUE THREAD

**Issue by annighoefer** [pyecore/pyecore#109]
I am not sure if this is a bug, but I was expecting that every EObject has eAnnotations. Currently, however, only Meta-Element (e.g. EClass, EAttribute, EReference,...) have eAnnotations in pyecore. 

    myClass = EClass('myClass')
    myClass.eAnnotations #works
    myObject = myClass()
    myObject.eAnnotations #fails

From all that I tried, I would say that Java behaves different. In Eclispe I can put annotations in my usermodel. 

If I am right, I would like to have eAnnotations of all EObjects.

**Comment by aranega** [comment]
Hi @annighoefer 

Sorry for the late answer, I didn't receive the notification.
From what I remember, `eAnnotations` are only on `EModelElement`, but it's not something shared by the instance level afterward. I will check ASAP on eclipse.

**Comment by aranega** [comment]
Hi again,

I checked quickly in Java I cannot add `eAnnotations` on any `EObject`

```java
EClass ec = EcoreFactory.eINSTANCE.createEClass();
ec.setName("MyClass");
		
EPackage pack = EcoreFactory.eINSTANCE.createEPackage();
pack.setNsPrefix("myclass");
pack.setName("myclass");
pack.setNsURI("http://testexample/1.0");
pack.getEClassifiers().add(ec);
		
EObject o = pack.getEFactoryInstance().create(ec);
o.getEAnnotations();   // This fails, there is no way of getting EAnnotations

// Trying to get the feature by reflection
EStructuralFeature eannotationsFeature = o.eClass().getEStructuralFeature("eAnnotations");
assert eannotationsFeature == null;  // the feature doesn't exist either
```

The only way I see to "propagate" the `eAnnotations` relationship to the instance level is to make `MyClass` inherit from `EModelElement` explicitaly:

```python
MyClass = EClass('MyClass', superclass=(EModelElement.eClass,))
myclass = MyClass()
myclass.eAnnotations
```

I acheived the same behavior in Eclipse, creating a `.ecore`, inheriting all "base metaclasses" from `EModelElement`, generating the metamodel code, then directly using `.getEAnnotations()`.

**Comment by annighoefer** [comment]
Thanks for investigating this. I can confirm you are right. Sorry, for bringing you on the wrong track. It would have been quite comfortable to have a universal way of adding attributes to every element.

**Comment by aranega** [comment]
No problem, I really had a doubt about it :sweat_smile:. It was good for me to refresh my memory.

Well, it will not be compatible with EMF, but as PyEcore is in Python, you can monkey patch it:

```python
EObject.eAnnotations = EModelElement.eAnnotations
EObject.eClass.eStructuralFeatures.append(EModelElement.eAnnotations)  # only to be sure it will serialize the data

myClass = EClass('myClass')
myObject = myClass()
myObject.eAnnotations  # works :)
```
But of course... this will not be compatible EMF-Java.

One of the point of PyEcore is to be able to use/reuse the open-class system of Python and to be able to patch/modify Ecore if needed.

**Comment by annighoefer** [comment]
For a long time, I rejected modifying the ecore model, but finally I found it handy to have EAnnotations everywhere. However, there are two shortcomings in your monkey path: (1) EAnnotation has an opposite reference to eModelElement. (2) the serialization does not consider features of EObject, because it is not a "real" superclass. I derived the following extended path that works for me so far. I do not know if it is the most elegant way, but I post it here is somebody has the same plans.

```python
def IsEObjectAnnotationsPatchEnabled():
    try: #test if the annotations have been added before
        test = EObject.eAnnotations
        return True
    except AttributeError:
        return False

def EnableEObjectAnnotationsPatch():
    try: #test if the annotations have been added before
        test = EObject.eAnnotations
    except AttributeError:
        # add eAnnotations to all eObjects
        EObject.eAnnotations = EReference('eAnnotations', EAnnotation, upper=-1, containment=True)
        EAnnotation.eObject = EReference('eObject', EObject, eOpposite=EObject.eAnnotations)
        EObject.eClass.eStructuralFeatures.append(EObject.eAnnotations)  # only to be sure it will serialize the data
        # EClass.findEStructuralFeature need a replacement, because it does not include EObject in the super type search hierarchy
        def findEStructuralFeaturePatch(self, name):
            #old part
            eFeature = next((f for f in self._eAllStructuralFeatures_gen()
                         if f.name == name),
                        None)
            #new part: see if it is part of EObject
            if(None==eFeature): 
                eFeature = next((f for f in EObject.eClass._eAllStructuralFeatures_gen()
                         if f.name == name),
                        None)
            return eFeature
        #patch the EClass method
        EClass.findEStructuralFeature = findEStructuralFeaturePatch
```

**Comment by aranega** [comment]
@annighoefer Wow! That's amazing! Yes, you're right, the face that `EObject` is not really a class in the inheritance per say for the feature lookup. Thanks so much for this, I plan to integrate it in the `utils` module in PyEcore, if you agree of course (I will add tests also). Thanks so much for your contributions every time :)

**Comment by annighoefer** [comment]
Your welcome. We benefit a lot from pyecore. Please feel free to use and/or improve the code as you like.
