### ISSUE TITLE
Hotfix: JsonResource fails with int values 

### ISSUE THREAD

**Issue by pablo-campillo** [pyecore/pyecore#110]
If an attribute is defined as EFloat but it is stored in a json file without any dot, that is, 13 or 34 instead of 13.0 or 34.0, they are parsed as int and instance building process fails giving the following message:

`Expected type EFloat(float), but got type int with value 3 instead for feature <EAttribute elevation:`

I've already fixed the issue adding the followint two lines in line 193 of pyecore.resources.json.py file:
```python
elif isinstance(value, int) and feature._eType.eType == float:
    inst.eSet(feature, float(value))
```

**Comment by aranega** [comment]
Hi Pablo,

Sorry for the late answer and thanks so much for the issue! I made a fix and I'm releasing a new hotfix version right now :)

**Comment by pablo-campillo** [comment]
Hi Vicent,

the fix works like a charm! :-) Congrats for your library its really useful for me! Thank you very much!

**Comment by aranega** [comment]
Thanks for the kind words :). I'm really glad all is working good for you!
