### ISSUE TITLE
EEnum definitions are serialized with the wrong EPackage

### ISSUE THREAD

**Issue by alessiostalla** [pyecore/pyecore#126]
E.g. in JSON:

```
"eType": {
    "eClass": "https://strumenta.com/kolasu/v2#//EEnum",
    "$ref": "#//IssueType"
}
```

Instead of `https://strumenta.com/kolasu/v2` we should have `http://www.eclipse.org/emf/2002/Ecore`.

**Comment by aranega** [comment]
Hi @alessiostalla ,

Wow, that's a really bad behavior... Thanks for reporting. Would you have a test case or something, I cannot reproduce the issue on my side (on the `develop` branch).

Here is a script example:

```python 
from pyecore.ecore import *
from pyecore.resources import ResourceSet
from pyecore.resources.json import JsonResource

eClass = EPackage('test', nsURI='http://test/1.0', nsPrefix='test')
nsURI = 'http://test/1.0'
nsPrefix = 'test'

BookCategory = EEnum('BookCategory', literals=['ScienceFiction', 'Biographie', 'Mistery'])
eClass.eClassifiers.append(BookCategory)

@EMetaclass
class A(object):
    names = EAttribute(eType=EString, upper=-1)
    bcat = EAttribute(eType=BookCategory)

rset = ResourceSet()
rset.resource_factory['json'] = lambda uri: JsonResource(indent=2, uri=uri)
resource = rset.create_resource('ZMM.json')
resource.append(eClass)
resource.save()
```
and the result I have

```json
{
  "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EPackage",
  "nsURI": "http://test/1.0",
  "name": "test",
  "nsPrefix": "test",
  "eClassifiers": [
    {
      "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EEnum",
      "name": "BookCategory",
      "eLiterals": [
        "ScienceFiction",
        "Biographie",
        "Mistery"
      ]
    },
    {
      "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EClass",
      "name": "A",
      "eStructuralFeatures": [
        {
          "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EAttribute",
          "name": "names",
          "eType": {
            "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EDataType",
            "$ref": "ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          },
          "upperBound": -1
        },
        {
          "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EAttribute",
          "name": "bcat",
          "eType": {
            "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EEnum",
            "$ref": "#//BookCategory"
          }
        }
      ]
    }
  ]
}
```
The `eClass` is properly set for the `EEnum`. Perhaps did you move the `EEnum` implementation to another package? Or you perhaps have a specific configuration that I need to tackle better.

**Comment by alessiostalla** [comment]
With the released version, I get:

```json
{
  "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EPackage",
  "name": "test",
  "nsPrefix": "test",
  "nsURI": "http://test/1.0",
  "eClassifiers": [
    {
      "eClass": "https://strumenta.com/kolasu/v2#//EEnum",
      "eLiterals": [
        "ScienceFiction",
        "Biographie",
        "Mistery"
      ],
      "name": "BookCategory"
    },
    {
      "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EClass",
      "name": "A",
      "eStructuralFeatures": [
        {
          "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EAttribute",
          "name": "names",
          "eType": {
            "eClass": "https://strumenta.com/kolasu/v2#//EDataType",
            "$ref": "#//EString"
          },
          "upperBound": -1
        },
        {
          "eClass": "http://www.eclipse.org/emf/2002/Ecore#//EAttribute",
          "name": "bcat",
          "eType": {
            "eClass": "https://strumenta.com/kolasu/v2#//EEnum",
            "$ref": "#//BookCategory"
          }
        }
      ]
    }
  ]
}
```

I don't understand where it's picking up the kolasu/v2 package though. I guess something in my code is polluting some registry.

**Comment by alessiostalla** [comment]
Ok so the issue stems from importing one package that has been created with pyecoregen that has two enum definitions in it:

```
name = 'StrumentaLanguageSupport'
nsURI = 'https://strumenta.com/kolasu/v2'
nsPrefix = ''

eClass = EPackage(name=name, nsURI=nsURI, nsPrefix=nsPrefix)

eClassifiers = {}
getEClassifier = partial(Ecore.getEClassifier, searchspace=eClassifiers)
IssueType = EEnum('IssueType', literals=['LEXICAL', 'SYNTACTIC', 'SEMANTIC'])

IssueSeverity = EEnum('IssueSeverity', literals=['ERROR', 'WARNING', 'INFO'])
```

and in the generated `__init.py__` we have:

```
otherClassifiers = [BigDecimal, BigInteger, IssueType, IssueSeverity]

for classif in otherClassifiers:
    eClassifiers[classif.name] = classif
    classif.ePackage = eClass
```

**Comment by aranega** [comment]
Aaah, I see. Nice catch, thanks so much for the use case. That sounds definitely like an issue with the way the code generation is done, but I need to review again the serializer and the Ecore metamodel to be sure on how to fix the problem and why this occurs. You could try to change 
`classif.ePackage = eClass` by `eClass.eClassifiers.append(classif)` to see if the issue still appear (if you have time). I will check that anyway asap !
 
Thanks again for the issue and the use case :)

**Comment by alessiostalla** [comment]
You're welcome :)
Unfortunately your suggested fix does not work because the relationship is bidirectional so adding to `eClass.eClassifiers` is the same as setting `classif.ePackage`.
FWIW, I fixed the issue (only in exports to JSON) with the following resource implementation:

```python
from pyecore.resources.json import JsonResource as BaseJsonResource

class JsonResource(BaseJsonResource):

    def open_out_stream(self, other=None):
        if isinstance(other, IOBase):
            return other
        else:
            return super().open_out_stream(other)

    @staticmethod
    def serialize_eclass(eclass):
        if eclass.name == "EEnum" and issubclass(eclass, EDataType):
            return f'{pyecore.ecore.nsURI}#//EEnum'
        else:
            return f'{eclass.eRoot().nsURI}{eclass.eURIFragment()}'

```

**Comment by aranega** [comment]
Yes, I suspected that changing the `ePackage` set wouldn't fix the issue, but just in case the bug came from another place :sweat_smile: 

I'll check that in depth because I don't remember I have issue with the XMI serializer, but I can mistake. Normally, the fact that the `ePackage` is written for the `EEnum` shouldn't be an issue, so perhaps there is something I miss somewhere else also.

Thanks so much for the lead on the fix in the `JsonResource` :) I hope I will understand well what's going on in my code and try to fix things as quick as possible.

**Comment by alessiostalla** [comment]
You're welcome :)
I don't understand it well, but it looks like an EClass instance lives in a package AND has its own eClass field for the EClass metaclass that lives in the Ecore package, while EEnum instances don't have this extra meta level. So while it works with EClasses not to hard-code anything because they are fully reflective, it doesn't work with EEnums, because the fact that the EEnum type itself lives in the Ecore package is not stated in an EEnum. Either you hard-code the fact that an EEnum's type (any EDataType's, really) lives in the Ecore package, or you have to store this meta-information somewhere in the EDataType itself.

Just my .02, thanks for the great work!
Alessio

**Comment by aranega** [comment]
Indeed, you're right, the fact that the instance is set into an instance of `EPackage` is always a little bit to wrap your head around.
`EEnum` are supposed to have this introspection/metalevel description anyway (see below), so I'm doing something wrong somewhere. I need to investigate more.

```python
>>> from pyecore.ecore import *
>>> BookCategory = EEnum('BookCategory', literals=['ScienceFiction', 'Biographie', 'Mistery'])
>>> BookCategory.eClass
<EClass name="EEnum">
>>> BookCategory.eClass.ePackage.nsURI
'http://www.eclipse.org/emf/2002/Ecore'
>>> pack = EPackage(nsURI='foo/1')
>>> pack.eClassifiers.append(BookCategory)
>>> BookCategory.ePackage.nsURI
'foo/1'
>>> BookCategory.eClass.ePackage.nsURI
'http://www.eclipse.org/emf/2002/Ecore'
```
Otherwise, the serialization of the dynamic metamodel would not work.
The way dynamic and static descriptions of `EENum` and `EClass` works is actually the same, so the problem comes probably from another point, there is perhaps a weird registration that I do at some point with static metamodels. I need to perform a little debug session I think :)

**Comment by alessiostalla** [comment]
Duh! I found it thanks to your pointers. It's really simple, pyecoregen generates the wrong code:

```python
for classif in otherClassifiers:
    eClassifiers[classif.name] = classif
    classif.ePackage = eClass

for classif in eClassifiers.values():
    eClass.eClassifiers.append(classif.eClass)
```

What happens is that, initially, `eClassifiers` is empty. Then, **first,** enums are added to `eClassifiers`, and **then** the `eClass` of each object in `eClassifiers` is added to the `EPackage` (that for some reason is called `eClass`). So we have the `EEnum` class added to the package we're defining!
I don't know the purpose of the second block, maybe it was to handle custom metaclasses or stuff like that, but it should filter the classes that it puts into `eClass`, or be removed altogether if it's not necessary.

**Comment by alessiostalla** [comment]
Closing this because it's not a Pyecore issue.
