### ISSUE TITLE
Reproducible attribute order

### ISSUE THREAD

**Issue by ubmarco** [pyecore/pyecore#127]
Thanks for this awesome library. I'm using it to build a bridge between [Sphinx-Needs](https://sphinx-needs.readthedocs.io) and EMF.
A requirement for me is to have reproducible pyecore serialization output for the same needs input which allows using diff tools on the XMI output.

This is currently not possible due to the random attribute order. I digged a little and found out the [EObject _isset member](https://github.com/pyecore/pyecore/blob/efdf500b0131812504bf5dfa7f63738dcce6bf0d/pyecore/ecore.py#L169) is a set.
When looping over it [here](https://github.com/pyecore/pyecore/blob/efdf500b0131812504bf5dfa7f63738dcce6bf0d/pyecore/resources/xmi.py#L418) the order is not determined.

I can think of 2 solutions:

- Preserve insertion order to _isset using a dictionary solution as outlined on [SO](https://stackoverflow.com/a/53657523/2285820). End users can populate fields in a specific order that would be preserved in the XMI output.
- Sort the attributes by the `name` field.

As a local workaround, I am running the following recursive function on the root model just before saving:

```python
def overwrite_isset(instance: EObject):
    """
    Replace instance._isset with a sorted list to get reproducable attribute order.

    This function should be called just before exporting as the list may functionally change
    the behavior of _isset.
    """
    if hasattr(instance, "_isset"):
        if instance._isset:  # pylint: disable=protected-access
            instance._isset = sorted(instance._isset, key=lambda x: (x.name))  # pylint: disable=protected-access
    for field in dir(instance):
        value = getattr(instance, field)
        if isinstance(value, EOrderedSet) and value.is_cont:
            for sub_instance in value.items:
                overwrite_isset(sub_instance)
```

**Comment by aranega** [comment]
Hi @ubmarco 

Thanks a lot for the ticket and the suggestion. Indeed, as you saw the `_isset` collection is a set as there is nothing in the XMI standard that implies that attributes should keep the same order (well, not from what I remember).
From the two solution you suggest, I suppose the best one would be the first. We can use an ordered set instead of a dict, I already use it and patched it to fit well with `EOrederedSet`, but I guess I was a little bit concerned about performances. Honestly, I don't think changing the collection type for `_isset` would have a huge impact. I need to make some tests about it to be sure, but I'm pretty certain it would not change so much. 

In any case, I'll try to integrate that asap (the main problem I have currently, is to find time), having equivalent output for sequence of serialization/deserialization would be really nice!

**Comment by aranega** [comment]
Regarding the first case, I have to check that. I rely on `lxml` for attribute parsing, but I know I delay some attribute resolution to later on (to overcome forward references in one pass only), so I have to do tests about it. For pure primitive types attributes, I think the order should be the same, but again, I have to test that.

The use of ordered set for case 2 will then imply that the order will be dependent on how data are written by a use. For example, for 

```python
inst1.name = 'foo'
inst1.location = 'earth'

inst2.location = 'mars'
inst2.name = 'bar'
```
In the XMI the order of primitive types attributes for `inst1` should be `name="..." location="..."` and for `inst2` should be `location="..." name="..."`. 

Another solution that could fit well otherwise is to use your second suggestion, sorting the names, but adding that as an XMI option that you can pass to the resource. Consequently, in a normal scenario, this would not impact serialization performances.

**Comment by aranega** [comment]
@ubmarco I quickly did some benchs, and using an `OrderedSet` instead of a `set` has a negative impact on performances. I think I'll go with the second solution then, adding the sorting as an option as it will only have an impact on the serialization.

**Comment by aranega** [comment]
I know, but I was always chilly to use them as I remember reading somewhere that it wasn't recommended to rely on that, or to use `OrderedDict`, but this latter has poor performances.
Regarding the API for dict, I don't think it will be a huge issue. Less clear in the code, surely however. I could subclass dict to add a `add` method, but I'm sure it will impact performances also (two lookups instead of one).
I'll try to evaluate asap what could be the impact in the code of changing for a dict

**Comment by aranega** [comment]
I made the change in `develop`, I subclassed `dict` only adding an alias to `setdefault` named `add` to keep consistent the API for people who are handling the `_isset` attribute (I know some people do). The rest of the API, mainly checking if there is element inside, or iterating on the keys doesn't change.

I didn't tested it yet, just included some code that was also on my computer since a while, and I droped Python 3.5 support.

I will test quickly if the attribute order is maintained between many serialization, but at the same time, could you check on your side when you have time if `develop` still reacts good? (I made some changes over the mro computation again) If you have a minimal example that triggers the new mro computation, that would be nice, I'm struggling to find a simple example.

**Comment by ubmarco** [comment]
I switched from `749f769` to `bc14d3e` and this leads to exceptions for certain fields. I cannot share that as my ECore model is private, however the exceptions look like:
```
AttributeError("'<ECore Class>' object has no attribute '<field>'")
```
In the debugger the fields are there, however accessing them lead to an exception. I guess they are properties and something goes wrong during lookup. I'm still investigating the root cause.

For MRO, I use the development branch because master gives me:
TypeError: Cannot create a consistent method resolution order (MRO) for bases <Base1>, <Base2>. However in the develop branch it works. Maybe I can derive a test model from mine. The latest develop commit `bc14d3e` can still load the M2/M1 model without problems.

**Comment by ubmarco** [comment]
[This line](https://github.com/pyecore/pyecore/blob/develop/pyecore/ecore.py#L884) leads to
```
TypeError('Metasubinstance._eAllBases_gen() takes 1 positional argument but 2 were given')
```

**Comment by aranega** [comment]
... The mro issue is so dumb, I changed location of some code and confused myself at the last moment during the commit... I'll fix that asap and try to add a test for that, but I struggle to reproduce a small example of the inheritance tree that can lead to the use of the new mro computation. I need to find back the metamodels I was using during my expérimentations. 

For the missing field, if you have a minimal example, that would be great, I don't see so well what could be the issue. Is the deserialization triggering the issue? Or serialization? Or is it related to the mro computation failing?

Sorry for the half-baked commits...

**Comment by ubmarco** [comment]
No worries, people living off a branch called `develop` won't expect each commit to work.

So I spend 2 hours bisecting my ECore and XMI model and generalizing it, so I can hand it out.
Here is my minimal failing example :)

ECore
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testns" nsURI="http://www.example.com" nsPrefix="testns">
  <eClassifiers xsi:type="ecore:EClass" name="Iface1" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FieldSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FieldUnset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iface2" abstract="true" interface="true"
      eSuperTypes="#//Iface1"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sub" eSuperTypes="#//Iface2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubSubs" upperBound="-1"
        eType="#//SubSub" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSub" eSuperTypes="#//Iface2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubSubSubs" upperBound="-1"
        eType="#//SubSubSub" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSubSub" eSuperTypes="#//Iface3"/>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//Sub">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Subs" upperBound="-1" eType="#//Sub"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSub2" eSuperTypes="#//SubSub"/>
  <eClassifiers xsi:type="ecore:EClass" name="Iface4" eSuperTypes="#//Iface1 #//Iface3"/>
  <eClassifiers xsi:type="ecore:EClass" name="Iface3" abstract="true" interface="true"
      eSuperTypes="#//Iface2"/>
</ecore:EPackage>
```
XMI
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
  xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:testns="http://www.example.com">
  <testns:Root xmi:id="uuid1">
    <Subs xmi:id="uuid2">
      <SubSubs xmi:id="uuid3"/>
      <SubSubs xsi:type="testns:SubSub2" xmi:id="uuid4">
        <SubSubSubs xmi:id="uuid5" FieldSet="Name of uuid5"/>
      </SubSubs>
    </Subs>
  </testns:Root>
</xmi:XMI>
```

When you instantiate the model, and look at 
```
Root.Subs.items[0].SubSubs.items[1].SubSubSubs.items[0]
```
in a debugger you'll see
```
FieldSet: 'Name of uuid5'
FieldUnset: AttributeError("'SubSubSub' object has no attribute 'FieldUnset'")
```

The problem goes away once I remove the `EClass` `Iface4`. This class is not used anywhere in the meta model, however it affects the outcome. Also when I set a value to `FieldUnset` then it appears in the debugger and the exception is gone.

I hope this helps. If I can do something else for you please tell me.

**Comment by ubmarco** [comment]
Awesome. Thanks for the fast-as-lightning fix, my tool works as expected with `79691d0`.
And sure, use the ECore/XMI as test case. Tell when/if I can test the attribute ordering.

**Comment by aranega** [comment]
In the state of the branch, you could be able to test the attribute ordering. I didn't test it myself yet, I just made the modification in the code to evaluate the impact and to see if it would break some tests, but I lacked time to experiment everything properly.

**Comment by ubmarco** [comment]
Just checked and the attribute order is still random. This not only affects primitive attributes but also containment members.
Let's say I have an ECore class `House` with the attributes `Address` (str), `Rooms` (many-containment of `Room` class) and `Floors` (many-containment of `Floor` class). The all `Rooms` might switch with all `Floors`. This makes sense, as they many-containment attributes just appear in _isset like the primitive attributes.

The random order might also stem from my own code. I mainly use dictionaries and lists for iteration, so order should be preserved, but I haven't checked explicitly.

I think adding another item `SORTED_ATTRIBUTE_ORDER` to `XMIOptions` would make sense anyway and is a quick solution to the problem when serializing. Just have to decide how to sort (natural vs plain alphabetical).
To go a little further, the option could also be a user defined sort callback that takes 2 items, compares and returns -1, 0, 1 (just like for `sorted`). That function could also implement arbitrary sorting (e.g. dependent on the ECore class of the items when providing another context parameter).

**Comment by ubmarco** [comment]
For reference, this is my natural sorting function that I use for `items` of many-containments:
```python
def natural_sort_in_place(list_to_sort, sort_field):
    """Sort a list by a given attribute naturally (correctly handling numbers)."""

    def convert(text):
        return int(text) if text.isdigit() else text.lower()

    def alphanum_key(key):
        return [convert(c) for c in re.split("([0-9]+)", getattr(key, sort_field))]

    list_to_sort.sort(key=alphanum_key)

```

**Comment by aranega** [comment]
I checked on my side, and I have a reproducible attribute order. As the dict keeps the insertion order, the serialization respects it and the deserialization also. 
Here is the code I used as example:

```python
from pyecore.resources import *
from pyecore.ecore import *


# small metamodel definition
A = EClass('A')
A.eStructuralFeatures.append(EAttribute('name', eType=EString))
A.eStructuralFeatures.append(EAttribute('location', eType=EString))
A.eStructuralFeatures.append(EAttribute('age', eType=EInt))

Root = EClass('Root')
Root.eStructuralFeatures.append(EReference('own', eType=A, upper=-1, containment=True))
Root.eStructuralFeatures.append(EReference('alternativeown', eType=A, upper=-1, containment=True))

Package = EPackage('Pack', nsURI='http://pack/1.0', nsPrefix='pack')
Package.eClassifiers.extend([Root, A])

# small instance model
a1 = A(name='foo', location='bar', age=42)  # will appear in this order: name, location, age
a2 = A(age=24, name='faz', location='boz')  # will appear in this order: age, name, location
a3 = A(location='bazz', name="fooz")  # will appear in this order: location, name

a4 = A()  # will appear in this order: name, location
a4.name = 'fooAlt'
a4.location = 'barAlt'
a5 = A(age=24, name='faz', location='boz')  # will appear in this order: age, location, name
a5.age = 24
a5.location = 'bozAlt'
a5.name = 'fazAlt'

root = Root()
root.own.extend([a1, a2, a3])  # first "own" with "a1, a2, a3"
root.alternativeown.extend([a4, a5])  # then "alternativeown" with "a4, a5"

# # alternative same order
# root = Root()
# root.own.append(a1)  # first "own" references
# root.alternativeown.append(a4)  # then "alternativeown" references
# root.own.append(a2)
# root.alternativeown.append(a5)
# root.own.append(a3)

# # alternative order
# root = Root()
# root.alternativeown.append(a4)  # first "alternativeown" references
# root.own.append(a1)  # then "own" references
# root.own.append(a2)
# root.alternativeown.append(a5)
# root.own.append(a3)

# serialize a first time
rset = ResourceSet()
resource = rset.create_resource('Z0.xmi')
resource.append(root)
resource.save()

# read in another resource set and serialize
# again under a new name
rset = ResourceSet()
rset.metamodel_registry[Package.nsURI] = Package
resource = rset.get_resource('Z0.xmi')  # read the serialized file
resource.contents[0].own[2].age = 99  # We add a new attribute that will be at the end, so: location, name, age
resource.save('Z1.xmi')  # Serialize again with the same order
```

and here is the XMI result for `Z0.xmi`. There is the same order for the attributes as anticipated, then reading/writing it again in another XMI keeps the same attribute order and the one I added after the derialization are added at the end.

```xmi
<?xml version='1.0' encoding='UTF-8'?>
<pack:Root xmlns:xmi="http://www.omg.org/XMI" xmlns:pack="http://pack/1.0" xmi:version="2.0">
  <own name="foo" location="bar" age="42"/>
  <own age="24" name="faz" location="boz"/>
  <own location="bazz" name="fooz"/>
  <alternativeown name="fooAlt" location="barAlt"/>
  <alternativeown age="24" name="fazAlt" location="bozAlt"/>
</pack:Root>
```

```xmi
<?xml version='1.0' encoding='UTF-8'?>
<pack:Root xmlns:xmi="http://www.omg.org/XMI" xmlns:pack="http://pack/1.0" xmi:version="2.0">
  <own name="foo" location="bar" age="42"/>
  <own age="24" name="faz" location="boz"/>
  <own location="bazz" name="fooz" age="99"/>
  <alternativeown name="fooAlt" location="barAlt"/>
  <alternativeown age="24" name="fazAlt" location="bozAlt"/>
</pack:Root>
```
It respects the insertion order of the attribute/references, making the result reproductible.

However, if you want the attribute sorted, indeed, it would be better to have an option for XMI, the standard does considers sorted attributes (again, not 100% sure, but almost).

**Comment by aranega** [comment]
@ubmarco wow, that's really a strange behavior... It shouldn't change nothing, reading from a `.ecore` or creating manually the metamodel is exactly the same (and with the static version, it's basically the same also). All objects are reflexive and have a meta level they use to autoconfigure themselves. At then end, every PyEcore object is an `EObject` where the `_isset` attribute is now a `dict`. On my code I don't have even references to `set` anymore for `_isset`:

```bash
$ grep -i 'set\(\)' pyecore
pyecore/commands.py
341:        self.resource_set = resource_set or ResourceSet()

pyecore/ecore.py
179:    _instances = WeakSet()
184:        instance._isset = InternalSet()
190:        instance._inverse_rels = set()
1018:        super().__setattr__('_inverse_rels', set())

$ grep -i '_isset' pyecore
pyecore/valuecontainer.py
116:        owner._isset[efeature] = None
219:        self.owner._isset[self.feature] = None
273:        self.owner._isset[self.feature] = None
293:        self.owner._isset[self.feature] = None
336:        self.owner._isset[self.feature] = None
358:        self.owner._isset[self.feature] = None
375:        self.owner._isset[self.feature] = None

pyecore/resources/json.py
244:        for attr in obj._isset:

pyecore/resources/xmi.py
419:        for feat in obj._isset:

pyecore/ecore.py
184:        instance._isset = InternalSet()
218:        return feature in self._isset
1136:ENamedElement.name._isset[ENamedElement.name] = None  # special case
1137:EString._isset[ENamedElement.name] = None  # special case
1195:ENamedElement.name._isset[ETypedElement.eType] = None  # special case
```
For example, using the `.ecore` and `.xmi` you shared with me as use case, and this script, I have `InternalSet` every times:

```python
from pyecore.resources import *

rset = ResourceSet()
resource = rset.get_resource('ZYX.ecore')
mmroot = resource.contents[0]
rset.metamodel_registry[mmroot.nsURI] = mmroot

resource = rset.get_resource("zyx.xmi")
root = resource.contents[0]
node = root.Subs.items[0].SubSubs.items[1].SubSubSubs.items[0]

print(type(node._isset))  # displays <class 'pyecore.innerutils.InternalSet'>
print(type(root.eClass()._isset))  # displays <class 'pyecore.innerutils.InternalSet'>
print(type(mmroot.getEClassifier('Root')()._isset))  # displays <class 'pyecore.innerutils.InternalSet'>
```

**Comment by aranega** [comment]
Hi @ubmarco , I pushed a the test for the MRO using your use case and I need to add a test for the reproductible order. Do you still have the strange issue with the type of the `_isset` collection not being the good one?

**Comment by aranega** [comment]
Beside the `CHANGELOG` and `README` update, it should be good for a new release (it will be `0.13.0`)

**Comment by ubmarco** [comment]
Big brain time on my side this time.
I have 2 virtualenvs, one for sphinx-emf and another one for the test Sphinx build. I updated the one for sphinx-emf with your new commit while VSCode launcher still pointed to the one from Sphinx. So I was using another commit of pyecore... thanks for your time and efforts on this one.

The attribute sorting in the order as defined in source code works perfectly fine.

**Comment by ubmarco** [comment]
Thanks again and looking forward to the new release!
