### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ubmarco** [pyecore/pyecore#128]
I'm interested in a new version of this library. Here is the current [delta from develop to 0.12.2](https://github.com/pyecore/pyecore/compare/0.12.2...develop).

I'm especially interested in the MRO commit.

Can this be done more sooner than later? I'm happy to help if there is something I can do.

**Comment by aranega** [comment]
Hi @ubmarco ,

As you saw, I'm a little bit late for releasing :sweat_smile:, as I stated in the other ticket, it's mainly a lack of free time, not really motivation. I'll try to do that asap with the integration of the ordered set for `_isset` and few other tickets I have still let on the side if they can be fixed quickly.

**Comment by ubmarco** [comment]
I really don't want to stress you at all. I highly appreciate any efforts that people put into open source projects, especially when they do it in their free time. So thanks a lot for any investment I can get from your side.

With regard to this issue, I would release the tool as it is without any new additions. The develop branch seems to work correctly and has valuable features/fixes. New features need more time to code and test.

Btw, if the release process is effort on your side, you may automate the release using a Github action. [Here](https://github.com/useblocks/sphinx-needs/blob/master/.github/workflows/release.yaml) is an example based on `poetry`. You just need to add the test-pypyi and pypi API key to the project's secrets. Then any create tag will lead to a new release.

**Comment by ubmarco** [comment]
Thanks for the update.
When looking at my own PR's [build](https://app.travis-ci.com/github/pyecore/pyecore/jobs/577352803), it looks like you should update `importlib-metadata` before installing `tox-travis` and `coveralls`. I would also update the requirements.txt file and pin all direct dependencies for reproducible tests.
setup.py can have open dependencies not to constrain dependent applications, but requirements.txt is about knowing what  version combination works.

**Comment by aranega** [comment]
Thanks for the pointer, the problem was indeed the `importlib-metadata` lib that required to be updated.

**Comment by aranega** [comment]
@ubmarco Thanks for your patience, a new version is here! I went with `0.13.0` at the end, I was afraid that a "hole" in the versions would make things weird for everyone. 

I went another time through the issues, there is others that I'll address soon, they are all interesting, but they require a little bit more time.

**Comment by ubmarco** [comment]
Nightshift-style, nice. Btw, it is really awesome to live on a planet where people have access to EMF from the Python world. Thanks for the work you do.
