### ISSUE TITLE
get all properties of a model element

### ISSUE THREAD

**Issue by Z-Rajaei** [pyecore/pyecore#131]
Hello,
I want to get all the properties of an element in the model.
```
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
```

for example, in the above ecore part. I want to know which properties the states EReference has. (i.e. name, upperbound, etype and containment and their values.)
what can I do in case I don't know which properties are specified to access them?

**Comment by alessiostalla** [comment]
You obtain the element's EClass, then query it, e.g.
```
myEObject.eClass.eAllStructuralFeatures()
```

**Comment by aranega** [comment]
I'll close the issue as @alessiostalla answered your question and we also exchanged a little bit by email :)
