### ISSUE TITLE
EOrderedList.clear() does not update references.

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#138]
Hi @aranega,

I've run into an issue with clearing an EOrderedList. When an EObject in the list has references to other EObjects, this reference is not cleared. The Meta model is as follows (see also [here](https://energytransition.github.io/) for the full meta model):

```mermaid
classDiagram
     direction LR
    class Asset 
    class  Port {
        <<abstract>>
    }
    Asset *--> "*" Port: port
    Port <|-- OutPort
    Port <|-- InPort
    InPort "*"  <--> "*" OutPort : connectedTo
```

In instance model would look like:
```mermaid
classDiagram
    direction LR 
    class Port1 {
        <<InPort>>
    }       
    class Port2 {
        <<OutPort>>
    }       
    Asset1 *--> "*" Port1: port
    Port1 "*" <--> "*" Port2 : connectedTo
    Asset2 *--> "*" Port2 : port
```

So if I now do a `clear()` on the port list of Asset 1, the `connectedTo` reference from Port1 to Port2 is not cleared, rendering an invalid model state.
If I iterate over all the ports in the `port` list and `delete()` them one by one using eobject.delete(), the references are updated correctly.

Looking at the code, the clear() method is implemented as follows in `valuecontainer.py`:
```python
    def clear(self):
        while self:
            elem = self.pop()

    def pop(self, index=None):
        if index is None:
            value = super().pop()
        else:
            value = super().pop(index)
        if self.is_ref:
            self._update_container(None, previous_value=value)
            self._update_opposite(value, self.owner, remove=True)
        self.owner.notify(Notification(old=value,
                                       feature=self.feature,
                                       kind=Kind.REMOVE))
```
What is missing here is that (when you compare this to `delete()` from `ecore.py`, a seek set is created and the connectedTo reference is handled correctly:

```python
    def delete(self, recursive=True):
        if recursive:
            for obj in self.eAllContents():
                obj.delete()
        seek = set(self._inverse_rels)
        # we also clean all the object references
        seek.update((self, ref) for ref in self.eClass.eAllReferences())
        for owner, feature in seek:
            fvalue = owner.eGet(feature)
            if feature.many:
                if self in fvalue:
                    fvalue.remove(self)
                    continue
                elif self is owner:
                    fvalue.clear()
                    continue
                value = next((val for val in fvalue
                              if getattr(val, '_wrapped', None) is self),
                             None)
                if value:
                    fvalue.remove(value)
            else:
                if self is fvalue or self is owner:
                    owner.eSet(feature, None)
                    continue
                value = (fvalue if getattr(fvalue, '_wrapped', None) is self
                         else None)
                if value:
                    owner.eSet(feature, None)
```

Any clue where we should make `clear()` a bit smarter?
Thanks!

**Comment by aranega** [comment]
Hi @ewoudwerkman Thanks for the issue and for pointing out this behavior. 

Actually, this a wanted behavior which is equivalent to the one in EMF. The `clear()` method on any `EList` like is meant to mimic the `removeAll()` from EMF-Java, which only removes the elements from the collection, but nothing else, it will not delete the other links. The `delete()`, as you saw, will delete all the references that are also made towards the object. 

If you really want to delete elements from a collection from your model, you should use `delete()` and iterate on all the elements of the collection if you want to delete all of them. The `clear()` is only here to manipulate the list and remove all elements inside, not more. 

Also, you can use the `clear()` to actually delete elements from your model if you go with the serialization. The serialization will not serialize elements that are not contained in a `EResource` (again as the EMF-Java version), so, in your case, if you "clear()" all elements from `port`, even if there is still in memory a relation between `port1` and `port2`, if you serialize your model (considering that all is in a `EResource`), then the relation between `port1` and `port2` will not be serialized in the XMI/JSON. If really, in memory you want to get rid of `port1`, then the `clear()` is not enough, and you need to use the `delete()`.

**Comment by ewoudwerkman** [comment]
Hi @aranega,

Thanks for the clarification. I think this is only an issue for bi-directional references (as is the connectedTo in my model).
Then my workaround with `delete()` is the way forward.

Thanks!

**Comment by aranega** [comment]
Indeed, in your case, for what you want to do (also clearing the bi-directional reference), the `delete()` seems more appropriate. The `clear()` would be more here to remove elements from one collection and to place them in another, or to pass them from a resource to another without loosing the links toward them.
