### ISSUE TITLE
Serialize datetime using JsonResource

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#139]
Hi @aranega,

I've run into an issue with serializing an EDate in a JsonResource. I get the following stacktrace:
```
Traceback (most recent call last):
  File "C:\data\git\esdl-mapeditor\tests\esdlproject\event_test.py", line 55, in test_track_changes
    resource.save(options=options)
  File "C:\data\git\esdl-mapeditor\venv\Lib\site-packages\pyecore\resources\json.py", line 58, in save
    stream.write(json.dumps(dict_list, indent=self.indent).encode('utf-8'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\data\software\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\data\software\Python\Python311\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "C:\data\software\Python\Python311\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\data\software\Python\Python311\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\data\software\Python\Python311\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\data\software\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

I would expect that the JsonResource somewhere used EDate.to_string() to serialize it to a string, similar to XMIResource, but the current approach seems different (leveraging `json.dumps(...)` build-in functionality).

As a quick hack I adapted the `save()` method to check if the options contain a json encoder and use that encoder to serialize datetime, but I think we can do better here. Any idea where it is best to change the code to support EDate in JsonResource?
BTW: decoding of dates in Json works.

My current changes:
```python
def save(...)
        ...
        if 'encoder' in self.options:
            stream.write(json.dumps(dict_list, indent=self.indent, cls=self.options['encoder'])
                         .encode('utf-8'))
        else:
            stream.write(json.dumps(dict_list, indent=self.indent).encode('utf-8'))
```
```python
class DateTimeEncoder(json.JSONEncoder):

    def default(self, obj):
        if isinstance(obj, (datetime.datetime, datetime.date, datetime.time)):
            return obj.isoformat()
        elif isinstance(obj, datetime.timedelta):
            return (datetime.datetime.min + obj).time().isoformat()

        return super(DateTimeEncoder, self).default(obj)
```
Example usage:
```
options = dict()
options['encoder'] = DateTimeEncoder
resource.save(options=options)
```

**Comment by edwinmat** [comment]
Hi @aranega, do you have any update on this issue?

**Comment by ewoudwerkman** [comment]
Hi @aranega 
I'm very sorry to hear that. My condolences! Take your time. 
For now we'll fix this in our own code and provide a PR for you to have a look at it later.
Take care!

**Comment by aranega** [comment]
Hi @ewoudwerkman @edwinmat ,

Sorry for the long delay. I find time to work on your issue, and I made a fix to properly call the `to_string` on `EDataType`. This is the way it should be, and it was a mistake (or a regression, I have memory to implement that at some point), from my side.

At the same time, I added the possibility to add custom encoder/decoder for the JSON resource, but with the fix, they are not so useful. As the JSONResource first convert everything in dict of basic types, I found difficult (to not say impossible) to trigger properly the encoder. It's still possible to overwrite the `encode(...)` method for example, but it means that you need to rewrite a huge part of the logic to have everything. I let them anyway, in case there is something I cannot see right now but that could serve you.

The code is on `develop` and there is two options `JsonOptions.DECODER` and `JsonOptions.ENCODER` that you can use to specify the encoder for the save, and the decoder for the load.

**Comment by aranega** [comment]
Hi @ewoudwerkman @edwinmat . I released a new version in the beginning of the week (I had to for another project that couldn't upgrade). The fix for the `to_string()` is in there, as well as the specific encoder/decoder. However, now that the `to_string` on `EDataType` is working, there is a lot of chances that the encoder you added in your base code will have no effect. To have the same behavior, you should override the `to_string` and `from_string` for the `EDate` data type, or you should create your own data type and code the `to_string/from_string` there. I'm sorry for the extra-work on this.

**Comment by ewoudwerkman** [comment]
Hi @aranega, Thanks for you changes! The `to_string()` suffices for our use case, so no extra work necessary.
