### ISSUE TITLE
EOrderedSet does not order elements

### ISSUE THREAD

**Issue by JulioDoAr** [pyecore/pyecore#146]
Firstly, I have been working with PyEcore recently, and I am glad that this exist. Thanks a lot for the work and
dedication presented here.

On the other hand, I have been struggling with some problems related to EOrderedSet because it does not have any order.
I am using the [Graph and Node elements in the docs](https://pyecore.readthedocs.io/en/latest/index.html) and, if you change the order
in wich nodes n1 and n2 are added to the graph, it changes the order of the list.

Is it the intended behaviour? Do I have a way to order the elements inside the EOrderedSet? 

I am working with hashing xmi documents and the order is vital to check when the xmi's are the same.

# Definition of elements

```python
from pyecore.ecore import EClass, EReference

# Definitions of Graph and Node
Graph = EClass('Graph')
Node = EClass('Node')
contains_nodes = EReference('nodes', Node, upper=-1, containment=True)
Graph.eStructuralFeatures.append(contains_nodes)
Node.eStructuralFeatures.append(EReference('owned_by', Graph, eOpposite=contains_nodes))

# Creation of 1 Graph and 2 Nodes
g1 = Graph(name='Graph 1')
n1 = Node(name='Node 1')
n2 = Node(name='Node 2')

# Code to change
# This code is wich I have been changing
g1.nodes.extend([n1, n2])  # Code of the example

# Print data
for node in g1.nodes:
    print(node.name)

print(g1.nodes)
```

# First execution

If you change the order in wich the EOrderedSet 'nodes' extends, it changes the order inside the Set.

## n1, n2

```python
g1.nodes.extend([n1, n2])

```

```
Node 1
Node 2
EOrderedSet([ < pyecore.ecore.Node object at 0x0000026C1DCA5160 >, < pyecore.ecore.Node object at 0x0000026C1D832D50 >])
```

## n2, n1

```python
g1.nodes.extend([n2, n1])
```

```
Node 2
Node 1
EOrderedSet([<pyecore.ecore.Node object at 0x000002CFCA392D50>, <pyecore.ecore.Node object at 0x000002CFCA7D5160>])
```

# Add method

I have checked to do it separately with the add function, but the behaviour is the same

## n1, n2

```python
g1.nodes.add(n1)
g1.nodes.add(n2)
```

```
Node 1
Node 2
EOrderedSet([<pyecore.ecore.Node object at 0x0000022172D55160>, <pyecore.ecore.Node object at 0x0000022172902D50>])
```

## n2, n1

```python
g1.nodes.add(n2)
g1.nodes.add(n1)
```

```
Node 2
Node 1
EOrderedSet([<pyecore.ecore.Node object at 0x000001B427782D50>, <pyecore.ecore.Node object at 0x000001B427BC5160>])
```

**Comment by aranega** [comment]
Hi @JulioDoAr, thanks a lot for the kind words, I really appreaciate :) and thanks for the ticket also!

The behavior that you are having with `EOrderedSet` is the one that is expected. The semantic of this collection is to keep the insertion order. When a `EReference` or `EAttribute` is created, the default value for the `ordered` property is `ordered=True` and the `unique` property is `unique=False`. What it means is that the collection considers that the order set by the user in the collection has meaning. 

So, `EOrderedSet` is not sorting elements, and ensure that if you read an XMI file, it will keep the same elements' order that is written in the XMI file. This is the same behavior than the one in EMF-Java. Theorically, all the `EReference` types collection behave the same as the one in EMF-Java (technically, there is a small modification on the way elements are accessed/iterated from for `ordered=False, unique=True`, so for `ESet` that kind of fallback on `EOrderedSet` implementation for retaining XMI structure when deserializing).

The only way you can have to order an `OrderedSet` would be to sort it. Under the hood, I'm using https://github.com/rspeer/ordered-set, I'm not sure the elements are sortable inside, but as it respects the `MutableSequence` interface, so you can call `sorted(..., key=...)` either on the collection before `extend` the `EOrderedSet`, or you can call `sorted` on the `EOrderedSet`. You'll get a simple list as output and the `EOrderedSet` will not be mutated, if you want to mutate it, there is currently no other choice than:

1. sorting the `EOrderedSet` and storing the result in a var
2. `.clear()` the `EOrderdSet`
3.  `.extend(...)` the `EOrderedSet` instance

In a general way, I guess an in-place `.sort()` method that wraps this behavior could be something interesting for PyEcore

**Comment by JulioDoAr** [comment]
Thank you very much for your quick response. The truth is that when I saw ‘OrderedSet’ I understood that it could be reordered under a given criterion.

Yesterday, at the end of the day I was working on that way you propose and from what I see, the temporary will remain as permanent :).

Thank you very much and I hope you will continue with the project.
