### ISSUE TITLE
Multiplicity in EParameter

### ISSUE THREAD

**Issue by ecba** [pyecore/pyecore#15]
Hi, 

I'm currently using the ``EParameter`` class of the ``pyecore`` library. I saw that this is a derived class of the ``ETypedElement`` class in which one has the option to determine a value for the upper/lower index. 
As far as I've seen, this is not possible in the definition of an ``EParameter`` directly, e.g. like

``` Python
p = Ecore.EParameter('p', eType= Ecore.EInt, required= True, lower = 0, upper = 5)
```
Are there any other possiblities to specify the multiplicity directly or would it be better to use ``Ecore.EList`` as the parameter type?
  
Thank you in advance!

**Comment by aranega** [comment]
Indeed, you should be able to set a multiplicity for each `EParameter`, I forgot to add it in the constructor.
At the moment, the only way of setting the `lower/upper` attributes is to set them after the creation:

    p = Ecore.EParameter('p', eType=Ecore.EInt, required=True)
    p.lowerBound = 0  # by default, lower should be 0
    p.upperBound = 5

This should do the trick, but keep in mind that, at the moment, there is no type/multiplicity checking for operation parameter yet.

I add the missing parameters for `EParameter` and `EOperation` today ;).

**Comment by ecba** [comment]
Thank you for the quick answer!

**Comment by aranega** [comment]
The fix and some tests have been pushed on `develop`, I'll see to make a new release very soon!
