### ISSUE TITLE
Drop Python 3.3 support?

### ISSUE THREAD

**Issue by aranega** [pyecore/pyecore#17]
I saw that the last version of `pytest` (3.3.0) drops Python 3.3 and 2.6 support. Moreover, many major distribution tends to include at least Python 3.4 as basic version.
 
So... should we drop Python 3.3 support for PyEcore? Unless there is some Python 3.3 afficionados, I would be in favor of dropping it, but still, I prefer asking before.

**Comment by moltob** [comment]
All for it. 3.3 had end of life in [September](https://mail.python.org/pipermail/python-dev/2017-July/148584.html). I think we could get rid of a few things, like the enum34 dependency...

**Comment by aranega** [comment]
Indeed, it would be great to drop enum34. I know that some people were using Python 3.3 few months back, but I suppose they probably had migrate since then. I will get rid of the dedicated code tomorrow (and also remove the 3.3 deps. for pyecoregen if you want).

**Comment by aranega** [comment]
Farewell Python 3.3
