### ISSUE TITLE
use pyecore to generate the notation model

### ISSUE THREAD

**Issue by CFAndy** [pyecore/pyecore#18]
I want to use pyecore to manipulate the notation model. 
I use pyecoregen to get the notation.py from standard [notation.ecore.](https://github.com/eclipse/gmf.notation/blob/master/org.eclipse.gmf.runtime.notation/model/notation.ecore) After that, I can't use the generated class to define a notation file and.  Would it be possible for you to add a tutorial about this?

**Comment by aranega** [comment]
Hi Andy,

Do you have errors during the code generation? Also, did you use the `pyecoregen` version from Pypi? If so, this version is a little "outdated", try the version that is on the `master` branch if you can.

I gave it a try, and I used the `master` branch version of `pyecoregen`, the generation was a sucess and an:

```python
import notation
```
worked just fine. However, I looked a little bit more into the metamodel and the code, there is some _gotchas_:

* currently, default values are not handed in the generated code. This is a feature I forgot. I quickly fixed this locally, and I need to submit a PR to @moltob (so if my code's ok, the patch should be quickly there). This is not a bit issue persay.
* the original code has some `@generated NOT` lines, meaning the code had been manually modified. This is not a big deal in itself, but as, in some part of the code, it change the way information are serialized and deserialiazed, this could be a problem.

For example, you can observe that for `RelativeBendpoints`. The `points` attribute is a `RelativeBendpointList` datatype which is a list of `RelativeBendPoint` (not expressed in the metamodel). These `RelativeBenPoint` have a dedicated serialization/deserialization "routine". This can be expressed with `pyecore` by providing the dedicated methods `from_string` and `to_string` for the `RelativeBendpointList` datatype. Once again, in this state, this is not a big deal if you don't use them, but if you try to deserialize an existing model, this will be an issue, and if you serialize a model you have created which use them, the resulting model will not be compatible with the original Java version.

Beside that, everything's fine :). To sum up, for this specific metamodel, the Python code generation is not "enough", some manual coding is required to match the Java behavior for serialization/deserialization. This said, I will provide some snippets as soon as possible for creating elements, serializing a "notation" model and deserializing one (of course, assuming that the aformentionned points are handled).

**Comment by moltob** [comment]
I missed pyecoregen on PyPI is lagging! Sorry about that. @aranega you're going to submit a PR as mentioned above or should I go ahead with creating a new version in the next few days?

**Comment by aranega** [comment]
Don't worry Mike, I also totally forgot the pypi release... I will submit a PR as soon as I have added tests for the new feature, probably tomorrow, so don't bother with a new version right now ;)

**Comment by CFAndy** [comment]
@aranega I use the pyecoregen  from PyPI. I will use the generated notation.py to add notation information about the model and save it in a seperate XMI file.  It will be really great if the new fix could solve the issue.  I would love to test it.

**Comment by aranega** [comment]
@CFAndy I pushed a little bit further the tests I made. The `notation.runtime` project is tricky, it modify some properties at runtime, but I succeeded to deserialize, modify and serialize again a test project I found on github. However, there is some modifications I had to perform by hand that are consequences of:

1. a current restriction of `pyecore/pyecoregen` (nothing too much painful to do, only add one line), 
1. a missing information in the serialized model by PyEcore when dealing with `href`,
1. a missing option for XMI serialization/deserialization,
1. manual code modifications that exist in `runtime.notation`.

For the point 1, the modification is pretty easy. This case is currently a kind of restriction of `pyecore/pyecoregen`, I will try to correct it someday, but at the moment, I don't know how to properly detect this case.

For the point 2 and 3, I will patch PyEcore and provide very quickly a new version, perhaps this week-end if I have some free time. Point 2 is already fixed in my local branch, and point 3 should be easy to deal with.

For the point 4 however, there is no other solution than manually add some code to deal with the 'extravaganza' of the `runtime.notation` project. For example, some properties are dynamically renamed. This information is buried in the code, and is not expressed in the metamodel: https://bugs.eclipse.org/bugs/show_bug.cgi?id=159226#c12. This is possible to deal with this PyEcore, but there is no automatic solution for this.

Here is the code I have at the moment. I use the `.ecorediag` which uses gmf-notation, and the `.ecore` from this address (this ecorediag gives the graphical representation of an ecore metamodel):
ecorediag -> https://gist.github.com/whirlwin/5347021 (named: footballmanagement.ecorediag)
ecore -> https://gist.github.com/whirlwin/5347275 (named: footballmanagement.ecore)

Please note that this code only works with the patches I currently have on my local branch

```Python
import notation
from pyecore.resources import ResourceSet


# Dynamically add the new property, otherwise the '.ecorediag'
# see https://bugs.eclipse.org/bugs/show_bug.cgi?id=159226#c12
notation.View.persistedChildren.name = 'children'
notation.View.children = notation.View.persistedChildren
notation.Diagram.persistedEdges.name = 'edges'
notation.Diagram.edges = notation.Diagram.persistedEdges


# This class is here to match the 'runtime.notation' project (not expressed in the metamodel)
# see: https://github.com/eclipse/gmf.notation/blob/master/org.eclipse.gmf.runtime.notation/src/org/eclipse/gmf/runtime/notation/datatype/RelativeBendpoint.java
# This class and functions define dedicated deserialization/serialization for the RelativeBendpointList
# so it match the 'runtime.notation' behavior
class BendPoint(object):
    def __init__(self, source_x, source_y, target_x, target_y):
        self.source_x = source_x
        self.source_y = source_y
        self.target_x = target_x
        self.target_y = target_y

    def __repr__(self):
        return '[{}, {}, {}, {}]'.format(self.source_x, self.source_y,
                                         self.target_x, self.target_y)


def from_str(s):
    result = []
    for line in s.split('$'):
        v = [int(i) for i in line[1:-1].split(',')]
        result.append(BendPoint(v[0], v[1], v[2], v[3]))
    return result


def to_str(o):
    s = '{o!r}'.format(o=o)
    return s.replace('], [', ']$[')[1:-1]


notation.RelativeBendpointList.from_string = from_str
notation.RelativeBendpointList.to_string = to_str


# From this point, this is basic PyEcore/EMF handling
# we create a resourceset and register the 'notation' metamodel
rset = ResourceSet()
rset.metamodel_registry[notation.nsURI] = notation

# we get the '.ecore' (not required if you don't follow the cross-references from the ecorediag)
# resource = rset.get_resource('footballmanagement.ecore')
# ecore_root = resource.contents[0]

# we get the ecorediag
resource = rset.get_resource('footballmanagement.ecorediag')
root = resource.contents[0]

# we get one 'Edge'
e = [x for x in root.eAllContents() if isinstance(x, notation.Edge)][0]
e.bendpoints.points.append(BendPoint(0, 0, 0, 0))

# just for test, we save the resource in another '.xmi'
resource.save(output='other.xmi')
```

Sorry about all of this, you picked a tough competitor to test PyEcore!

**Comment by moltob** [comment]
pyecoregen 0.4.3 has been published on PyPI.

**Comment by aranega** [comment]
@moltob Wow, already? Thanks a lot Mike, that's awesome!

@CFAndy I will release the PyEcore patches today on github and Pypi. Once everything's online, I will  write a short "comprehensive guide" for your case asap.

**Comment by aranega** [comment]
@CFAndy I had a little bit of time today (god bless benchmarking on huge models), and I wrote a little "tutorial/how to" that should guide you for the GMF notation generation and part of its required manual modification: [read it here](https://gist.github.com/aranega/89dcc45b908babfdd02b9e70c9fcbe49).

Hope this help!

**Comment by CFAndy** [comment]
@aranega  Your tutorial is really great. Following your steps, I still meet following error. 
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    resource = rset.get_resource('test2.xmi')
  File "C:\Users\test\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\resources\resource.py", line 81, in get_resource
    resource.load(options=options)
  File "C:\Users\test\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\resources\xmi.py", line 38, in load

    modelroot = self._init_modelroot(xmlroot)
  File "C:\Users\test\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\resources\xmi.py", line 102, in _init_modelroot
    modelroot.__setattr__(key, value)
  File "C:\Users\fchen7\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\ecore.py", line 915, in __set__
    instance_dict[name]._set(value)
  File "C:\Users\fchen7\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\ecore.py", line 329, in _set
    self.check(value)
  File "C:\Users\fchen7\AppData\Local\Continuum\Anaconda3\lib\site-packages\pyecore\ecore.py", line 305, in check
    raise BadValueError(value, self._efeature.eType)
pyecore.ecore.BadValueError: Expected type EBoolean(bool), but got type str with value true instead

following is the test2.xmi code:

<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmi:id="_lfnFMAZOEeiaN5qMG_RJfw" visible="true" type="aaaa" name="bbbb#_lfgXgQZOEeiaN5qMG_RJfw" measurementUnit="Pixel">


  <children xmi:id="_gNTBkAZPEeiaN5qMG_RJfw" visible="true" type="2002">
    <children xmi:id="_gNTBlgZPEeiaN5qMG_RJfw" visible="true" type="5002">
      <styles xsi:type="notation:ShapeStyle" xmi:id="_gNTBlwZPEeiaN5qMG_RJfw" fontColor="0" fontName="Segoe UI" fontHeight="8" bold="false" italic="false" underline="false" strikeThrough="false" description="" fillColor="16777215" transparency="-1" lineColor="0" lineWidth="-1" roundedBendpointsRadius="0"/>
      <layoutConstraint xsi:type="notation:Location" xmi:id="_gNTBmAZPEeiaN5qMG_RJfw" x="-5" y="20"/>
    </children>
    <styles xsi:type="notation:FontStyle" xmi:id="_gNTBkQZPEeiaN5qMG_RJfw" fontColor="0" fontName="Segoe UI" fontHeight="8" bold="false" italic="false" underline="false" strikeThrough="false"/>
    <styles xsi:type="notation:LineStyle" xmi:id="_gNTBkgZPEeiaN5qMG_RJfw" lineColor="0" lineWidth="-1"/>
    <styles xsi:type="notation:DescriptionStyle" xmi:id="_gNTBkwZPEeiaN5qMG_RJfw" description=""/>
    <styles xsi:type="notation:IntValueStyle" xmi:id="_gNTBlAZPEeiaN5qMG_RJfw" name="Rotated_Style"/>
    <element href="bbbb#_gNRMYAZPEeiaN5qMG_RJfw"/>
    <layoutConstraint xsi:type="notation:Bounds" xmi:id="_gNTBlQZPEeiaN5qMG_RJfw" x="427" y="250" width="-1" height="-1"/>
  </children>
    <edges xmi:id="_nsbFmQZPEeiaN5qMG_RJfw" visible="true" type="4022" source="_nsbFkAZPEeiaN5qMG_RJfw" target="_eInNAAZPEeiaN5qMG_RJfw">
    <styles xsi:type="notation:ConnectorStyle" xmi:id="_nsbFmgZPEeiaN5qMG_RJfw" roundedBendpointsRadius="0" routing="Rectilinear" smoothness="More" avoidObstructions="false" closestDistance="false" jumpLinkStatus="None" jumpLinkType="Semicircle" jumpLinksReverse="false" lineColor="16738622" lineWidth="-1"/>
    <element xsi:nil="true"/>
    <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_nsbFmwZPEeiaN5qMG_RJfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
  </edges>
 
  
</notation:Diagram>


following is my python code:
import notation

notation.View.persistedChildren.name = 'children'
notation.View.children = notation.View.persistedChildren
notation.Diagram.persistedEdges.name = 'edges'
notation.Diagram.edges = notation.Diagram.persistedEdges
class BendPoint(object):
    def __init__(self, source_x, source_y, target_x, target_y):
        self.source_x = source_x 
        self.source_y = source_y
        self.target_x = target_x
        self.target_y = target_y
    def __repr__(self): 
        return '[{}, {}, {}, {}]'.format(self.source_x, self.source_y, self.target_x, self.target_y)
def from_str(s):
    result = []
    for line in s.split('$'):
        v = [int(i) for i in line[1:-1].split(',')] 
        result.append(BendPoint(v[0], v[1], v[2], v[3])) 
    return result
def to_str(o):
    s = '{o!r}'.format(o=o)
    return s.replace('], [', ']$[')[1:-1]

notation.RelativeBendpointList.from_string = from_str
notation.RelativeBendpointList.to_string = to_str
from pyecore.resources import ResourceSet
rset = ResourceSet()
rset.metamodel_registry[notation.nsURI] = notation  # register the notation metamodel

resource = rset.get_resource('test2.xmi')
root = resource.contents[0]

I guess one from_str is missing.

**Comment by aranega** [comment]
@CFAndy you're right! There was a missing call to the `from_string(...)` method of a datatype for the root element in an XMI during deserialization. Sorry about that... I fixed this behavior in PyEcore and published a new version on Pypi, you can `pip install pyecore -U` in order to get the last version with the patch. This time, your model should open properly.

**Comment by CFAndy** [comment]
@aranega  0.7.13 works like a charm.
Regarding to your very helpful tutorial, do you think it would be good to recommand user to add your following code to the __init__.py under package notation?  

notation.View.persistedChildren.name = 'children'
notation.View.children = notation.View.persistedChildren
notation.Diagram.persistedEdges.name = 'edges'
notation.Diagram.edges = notation.Diagram.persistedEdges
class BendPoint(object):
    def __init__(self, source_x, source_y, target_x, target_y):
        self.source_x = source_x 
        self.source_y = source_y
        self.target_x = target_x
        self.target_y = target_y
    def __repr__(self): 
        return '[{}, {}, {}, {}]'.format(self.source_x, self.source_y, self.target_x, self.target_y)
def from_str(s):
    result = []
    for line in s.split('$'):
        v = [int(i) for i in line[1:-1].split(',')] 
        result.append(BendPoint(v[0], v[1], v[2], v[3])) 
    return result
def to_str(o):
    s = '{o!r}'.format(o=o)
    return s.replace('], [', ']$[')[1:-1]

notation.RelativeBendpointList.from_string = from_str
notation.RelativeBendpointList.to_string = to_str

**Comment by aranega** [comment]
@CFAndy I'm glad the new version's working fine for you! Regarding the best placement for the "patching" code, I must say I don't know. I'm not a big fan of directly adding this to the `__init__.py` file. Instead, I would probably prefer creating a `notation_patch.py` file, put it under the `notation` package and import it in the `__init__.py` without forgetting to add the `BendPoint` class to the `__all__` variable. This solution works, but if the code you need to manually add to the metamodel becomes longer (for example, you need to implement some `create_...` method that are defined in the `notation` metamodel), I would probably prefer a little bit more complex solution but which would be more flexible.

I would use the `--user-module <path>` option from pyecoregen (you can look the description on the pyecoregen page). It should give something like this:
```bash
$ pyecoregen -e notation.ecore -o . --user-module "notation_behavior.mixins"
```
I would then create the `notation_behavior` package (name is not great), with a `mixins.py` module inside, and copy the code generated under `notation/notation_mixins.py.skel` inside `mixins.py`. This way, I could modify the mixin code and add all the behavior I need. In this module, I would also add the `BendPoint` class and the two `from_str(...), to_str(...)` function (but renamed).
Then, in this same package, I would create a `notation_patch.py` module, with this code

```python
import notation
from notation_behavior.mixins import from_str, to_str

notation.View.persistedChildren.name = 'children'
notation.View.children = notation.View.persistedChildren
notation.Diagram.persistedEdges.name = 'edges'
notation.Diagram.edges = notation.Diagram.persistedEdges

notation.RelativeBendpointList.from_string = from_str
notation.RelativeBendpointList.to_string = to_str
```

And finally, I would modify the `notation/__init__.py` by adding:

```python
from notation_behavior.mixins import BendPoint
import notation_behavior.notation_patch
__all__ = ['Edge', ..., 'BendPoint']
```
This solution is more complexe, but it gives you the ability to delete the generated code if you need to (for some reasons), without impacting too much your existing code. I didn't test it, so perhaps it requires some adjustments.

@moltob you have usually better solutions than mine, specially for this kind of problems. Perhaps you see a better way of doing this?

**Comment by suntao2012** [comment]
if I want to generate following test.xmi file with pyecore,
following is test.xmi
```
<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmi:id="_XbDa34kySUPRuSJnFG4h6p" visible="true" type="CofluentApplication" name="abc.cf_app_di#_3OXZdaUsdm1sYOWA1lTNO1" measurementUnit="Pixel">
  <styles xsi:type="notation:DiagramStyle" xmi:id="_6R7nxRJOiJCGkdTkKhtqP4" pageX="0" pageY="0" pageWidth="100" pageHeight="100" description=""/>
  <element href="abc.cf_app#_Q2RJLc0JKcso5QJ3TvF4bB"/>
</notation:Diagram>
```

I followed your steps, with this code
```
import notation
from pyecore.resources.xmi import XMIResource
from pyecore.resources import URI

root = notation.Diagram(name='root')
dstyle = notation.DiagramStyle()
dstyle.pageX = 0
dstyle.pageY = 0
dstyle.pageWidth = 100
dstyle.pageHeight = 100
dstyle.description = ""
root.styles.append(dstyle)

resource=XMIResource(URI('root.xmi'))
resource.append(root)
resource.save()
```

then, i only got root.xmi like this
```
<?xml version='1.0' encoding='UTF-8'?>
<notation:Diagram xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmi:version="2.0" name="root">
  <styles xsi:type="notation:DiagramStyle" pageWidth="100" pageHeight="100" description=""/>
</notation:Diagram>
```

if I want to add xmi:id attribute and element node, what should i do?

**Comment by aranega** [comment]
@suntao2012 In your case, your code misses some attributes about the root `measurementUnit` and `type` that can be filled the same way you did for `pageX` ...etc or using the constructor:

```python
dstyle = notation.DiagramStyle(measurementUnit=notation.MeasurementUnit.Pixel)
```

Regarding the `xmi:id` attribute, you need to add this option to the `XMIResource`:

```python
resource = XMIResource(URI('root.xmi'), use_uuid=True)
# or
resource = XMIResource(URI('root.xmi'))
resource.use_uuid = True
```

I will add this to the documentation for the next version. 

About the `element`, actually, this attribute is set if you "link" your graphical element to another. It could be an element in your model (but it has no interest here), or it could be an element in another model. To do this, it is better to build your `Resource` using a `ResourceSet` so each `Resource` that are referencing each other are in the same "container". In your case, this should work:

```python
rset = ResourceSet()
# here you load the model you want to reference
referenced_model_resource = rset.get_resource(URI('my_model.xmi'))  # at this point, be sure that the metamodel of 'my_model' is registered in the 'metamodel_registry' of the 'rset' or in the 'global_registry'
referenced_root = referenced_model_resource.contents[0]

# here is the resource for your notation model
resource = rset.create_resource(URI('root.xmi'))
resource.use_uuid = True

root = notation.Diagram(name='root) 
# ... your code for dstyle and root
root.element = referenced_root  # if you want to reference the root of the other model
resource.append(root)
resource.save()
``` 

Finally, If you want to have the `use_uuid` set for all your xmi wathever their "kind", you can override the `resource_factory` entry for `xmi` of your `ResourceSet` (you can also do it globaly) before creating the resources:

```python
 rset.resource_factory['xmi'] = lambda uri: XMIResource(uri, use_uuid=True)
 rset.resource_factory['*'] = lambda uri: XMIResource(uri, use_uuid=True)  # this will create a 'uuid aware' xmi resource for any other model extension you could have
 ```

**Comment by suntao2012** [comment]
@aranega very thanks. and I have added uuid successfully with your answer.
in addition, I still meet some problems, it would be nice if you have time to help me.
actually, I want to write 2 xml files with pyecore, the one xml is reference to the other. here are two xml example, `usecase.cf_app` like this
```
<?xml version="1.0" encoding="UTF-8"?>
<cofluent:Application xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cofluent="http://cofluent.intel.com/cofluent/1.0.0" xmi:id="_fe7YQB0PEei_PskjR9F_mQ" name="usecase" version="7.0.2_r1_20171218-1538" target="" cyclePeriod="10 ns" affinity="0" priority="1" staticCodeSize="0 kB" staticDataSize="0 kB" staticPowerConsumption="0 uW" dynamicPowerConsumption="0 uW" cost="0 USD" dynamicResourceLoad="100">
  <annotations xmi:id="_ffdjwB0PEei_PskjR9F_mQ" source="cdt.configurations">
    <details xmi:id="_ffdjwR0PEei_PskjR9F_mQ" key="cofluent.managedbuild.config.gnu.mingw.exe.release.1359416546" value="cdt.configuration.active"/>
  </annotations>
  <refinement xsi:type="cofluent:Structure" xmi:id="_fe7YQR0PEei_PskjR9F_mQ" name="usecaseSt"/>
</cofluent:Application>
```
 and `usecase.cf_app_di` like this
```
<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmi:id="_fe7_UB0PEei_PskjR9F_mQ" visible="true" type="CofluentApplication" name="usecase.cf_app_di" measurementUnit="Pixel">
  <styles xsi:type="notation:DiagramStyle" xmi:id="_fe7_UR0PEei_PskjR9F_mQ" pageX="0" pageY="0" pageWidth="100" pageHeight="100" description=""/>
  <element href="usecase.cf_app#_fe7YQR0PEei_PskjR9F_mQ"/>
</notation:Diagram>
```
if I have already generated `usecase.cf_app` file, I want to generate the `usecase.cf_app_di` with the element reference to refinement uuid in `usecase.cf_app`. because of the different nsURI, I meet some problems. here is my code.
```
rset = ResourceSet()
rset.metamodel_registry[cofluent.nsURI] = cofluent
# here you load the model you want to reference
referenced_model_resource = rset.get_resource(URI('usecase.cf_app'))  # at this point, be sure that the metamodel of 'my_model' is registered in the 'metamodel_registry' of the 'rset' or in the 'global_registry'
referenced_root = referenced_model_resource.contents[0]

rset.metamodel_registry[notation.nsURI] = notation
# here is the resource for your notation model
resource = rset.create_resource(URI('usecase.cf_app_di'))
resource.use_uuid = True

root = notation.Diagram(name='usecase', visible=True, type="CofluentApplication", measurementUnit=notation.MeasurementUnit.Pixel) 
# ... your code for dstyle and root
dstyle = notation.DiagramStyle(pageX=0, pageY=0, pageWidth=100, pageHeight=100, description="")
root.styles.append(dstyle)
root.element = referenced_root.refinement  # if you want to reference the root of the other model
resource.append(root)
resource.save()
```
the code run with error like this
```
Traceback (most recent call last):
  File "c.py", line 37, in <module>
    resource.save()
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore-0.7.13-py3.4.egg/pyecore/resources/xmi.py", line 302, in save
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore-0.7.13-py3.4.egg/pyecore/resources/xmi.py", line 383, in _go_across
  File "/home/suntao/PY3ENV/lib/python3.4/site-packages/pyecore-0.7.13-py3.4.egg/pyecore/resources/xmi.py", line 312, in _add_explicit_type
KeyError: 'http://cofluent.intel.com/cofluent/1.0.0'
```
it runs well when I remove `root.element=referenced_root.refinement`, so, I add reference element in a wrong way.

**Comment by aranega** [comment]
@suntao2012 It seems that there is an issue with the nsmap computation when heterogeneous model with cross-references are used. I will patch that, include new tests and release a new version asap! Sorry for the inconvenience...

**Comment by aranega** [comment]
@suntao2012 I released a new PyEcore version on Pypi: `0.7.14`. This version includes the patches to deal with heterogeneous models during XMI serialization, and it handles namespaces better than the previous version. A little `pip install pyecore -U` and your issue should be fixed!

**Comment by suntao2012** [comment]
@aranega the new version works well on heterogeneous model. thanks.

another question, I want to create an edge between 2 nodes, 2 nodes are from the same model, which like this
```
<children xmi:id="96c78b13-1870-421f-8ae5-9b56bb868b93" visible="true" type="3022">
  <styles xsi:type="notation:DescriptionStyle" xmi:id="d079c5f0-9b95-447e-ace9-56f007f834a0" description=""/>
  <styles xsi:type="notation:LineStyle" xmi:id="4839ac4a-ebef-4e73-8e20-74ff8338d27e" lineColor="11579568" lineWidth="-1"/>
  <layoutConstraint xsi:type="notation:Bounds" xmi:id="019f9830-10a5-405f-9df4-a17c23fbddda" x="44" y="23" width="-1" height="-1"/>
</children>
<children xmi:id="725ef765-b79d-46ec-8550-68209e14416c" visible="true" type="3016">
  <children xmi:id="2602e955-b21d-47a7-a351-90b1d8cc10b0" visible="true" type="5008"/>
  <styles xsi:type="notation:ShapeStyle" xmi:id="8d697da4-7f19-486c-84d0-00331d95a80e" fontColor="0" fontName="Segoe UI" fontHeight="8" bold="false" italic="false" underline="false" strikeThrough="false" description="" fillColor="16777215" transparency="-1" lineColor="11579568" lineWidth="-1" roundedBendpointsRadius="0"/>
  <element href="usecase.cf_app#_WnxgkB3vEei3uf4nsfGk5Q"/>
  <layoutConstraint xsi:type="notation:Bounds" xmi:id="6b0b0d3f-18e9-477a-a7eb-59d1cebcaf1b" x="49" y="51" width="-1" height="-1"/>
</children>
```
I want to create an edge from the first node to the second node, like this
```
<edges xmi:id="_vgGFAB3vEei3uf4nsfGk5Q" visible="true" type="4003" source="96c78b13-1870-421f-8ae5-9b56bb868b93" target="725ef765-b79d-46ec-8550-68209e14416c">
  <styles xsi:type="notation:ConnectorStyle" xmi:id="_vgGFAR3vEei3uf4nsfGk5Q" roundedBendpointsRadius="0" routing="Rectilinear" smoothness="None" avoidObstructions="false" closestDistance="false" jumpLinkStatus="None" jumpLinkType="Semicircle" jumpLinksReverse="false" lineColor="0" lineWidth="-1"/>
  <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_vgGFAh3vEei3uf4nsfGk5Q" points="[590, 341, 556, 319]$[617, 357, 583, 335]"/>
</edges>
```

here is my code, but I don't know how to create bendpoints and add it to edge node, and how do I add source/target node id to edge attribute?
```
edge_node_root = notation.Edge(visible=True, type="4003")
edge_node_root.styles.append(notation.ConnectorStyle(roundedBendpointsRadius=0, routing="Rectilinear", smoothness=notation.Smoothness.None_, avoidObstructions=False, closestDistance=False, jumpLinkStatus=notation.JumpLinkStatus.None_, jumpLinkType="Semicircle", jumpLinksReverse=False, lineColor=0, lineWidth=-1))
```

**Comment by aranega** [comment]
@suntao2012 The use of bendpoints is a little bit tricky with gmf notation as they put some manual logic in the original metamodel code. 
If you followed the small guide I wrote, you should have a `BendPoint` class with a dedicated `from_string` and `to_string` methods. For the example her, I put it in the code so I can access it using `notation.BenPoint`. You will have to adapt the snippet.

```python
bendpoints = notation.RelativeBendpoints()
bendpoints.points = [
    notation.BendPoint(590, 341, 556, 319),
    notation.BendPoint(617, 357, 583, 335)
]
```
For the explanation, each bendpoint is gathered in a `RelativeBenpoints` object, and stored in the `points` attribute in a list.

Then, you can add the `bendpoints` to your `edge_node_root`:

```python
edge_node_root.bendpoints = bendpoints
```

For setting the `source` and `target`, this is the same idea than for the `benpoints`, you can simply do:

```python
edge_node_root.source = ...  # your source object
edge_node_root.targe = ...  # your target object
```

**Comment by suntao2012** [comment]
@aranega thanks, it helped. I have created the edge.
if I want to set the edge element as true like this, how do I do
```
<edges xmi:id="_r1YkcR4IEei3uf4nsfGk5Q" visible="true" type="4003" source="c0120d2c-5935-48ed-8760-5428e979f3c9" target="63276080-a8de-4487-9bdb-53da04f178e3">
  <styles xsi:type="notation:ConnectorStyle" xmi:id="_r1Ykch4IEei3uf4nsfGk5Q" roundedBendpointsRadius="0" routing="Rectilinear" smoothness="None" avoidObstructions="false" closestDistance="false" jumpLinkStatus="None" jumpLinkType="Semicircle" jumpLinksReverse="false" lineColor="0" lineWidth="-1"/>
  <element xsi:nil="true"/>
  <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_r1Ykcx4IEei3uf4nsfGk5Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
</edges>
```

**Comment by aranega** [comment]
@suntao2012 Regarding the `xsi:nil="true"`, I must say that I don't know exactly how to insert it. From what I saw, it is XML to express the fact that the value had been set to null ententionnaly. To be honest, at this point, I don't know yet how to deal with it, and there is currently no way of adding it manually. I will check for the next version if I can find a way.

For your second question, as you saw, PyEcore does not serialize values that are set to the default one. I added an option for the json serializer, so I will add the same option for the XMI serializer asap. This options should also impact the `xsi:nil="true"` production, but for the first version I don't think I will be able to deal with it.

**Comment by aranega** [comment]
@suntao2012 Sorry for the delay, I had a lot going one lately. I pushed a patch and a new version on pypi (`0.7.16`, I failed the `0.7.15` on a typo... `nill` instead of `nil`...) that:

* lets you serialize default values with an option,
* creates the special XML node `xsi:nil="true"` if the aforementioned option is used and the feature is explicitly set to `None`. 

The patch is a little bit ugly at the moment, but that'll do the work.
You can `pip install pyecore -U`, and then, to set the `xsi:nil` stuff on `edge` for `element`, you can do:

```python
edge.element = None
```

and pass the `XMIOptions.SERIALIZE_DEFAULT_VALUES` to the `save()` method like this:

```python
from pyecore.resources.xmi import XMIOptions

# ... your code here and at the end
resource.save(options={XMIOptions.SERIALIZE_DEFAULT_VALUE: True})
```

I also quickly tested it on GMF runtime and the model seems to be created as it should.

**Comment by suntao2012** [comment]
@aranega that works! thanks a lot!
