### ISSUE TITLE
How can I create a dynamic model with Epackage?

### ISSUE THREAD

**Issue by lordrubenbp** [pyecore/pyecore#20]
Hi, could you give an example of how to create a dynamic model with an Epackage?. I don't know how to add EClass to my Epackage.

Many thanks and congratulations to the creator for a great job

**Comment by aranega** [comment]
Hi @lordrubenbp, sorry about the late answer.

To create a dynamic `EClass` and add it to a dynamic `EPackage`, you need to use the `eClassifiers` relation. Here is an example that creates a `Node` metaclass, and adds it to an `EPackage` instance:

```python
from pyecore.ecore import EPackage, EClass

mypackage = EPackage('mypackage', nsURI='http://mypackage/1.0', nsPrefix='mypackage')
Node = EClass('Node')

mypackage.eClassifiers.append(Node)  # here Node is added to the eClassifiers relation from the EPackage instance
```

The `eClassifiers` relation is a containment collection that can hold `EClass` and `EEnum`.

**Comment by lordrubenbp** [comment]
Thank you very much for your prompt response, it has been very helpful to me.!
