### ISSUE TITLE
How to read the contents of an imported model

### ISSUE THREAD

**Issue by lordrubenbp** [pyecore/pyecore#21]
Hello, I've been reading the documentation and it's not clear to me how to import an existing model.

I want to import the model and be able to read each of its components, but in the documentation it only appears how to rescue the main node and add, not read its contents. 

How could I do this?

Thank you very much for your help

**Comment by aranega** [comment]
Hi!

You're right, this is probably not clear in the documentation, I will add clarification and some example in the next version (perhaps some [repl.it](https://repl.it/languages/python3) examples also as repl.it nows properly supports pypi packages). Here is some information, I hope it will help!

Actually, once a model is deserialized, the content each model element is in memory, and you can access each element's value using the name of the meta-attribute/reference, exactly how you would do it when handling an instance.

For example, if we consider a "Graph" metamodel like [this one](https://repository.genmymodel.com/vincent.aranega/NodeGraph), from the root (which would probably be a `Graph`), you will be able to get the value of `name` attribute and the `nodes` attribute using their name (so if we named the root `g`, using `g.name` or `g.nodes`) . Here is how you can deserialize a model named `mymodel.xmi` that conforms to this metamodel. To read values from elements, it would work this way:

```Python
from pyecore.resources import ResourceSet, URI

# we consider here an existing ResourceSet named rset that is properly configured to 'known' about the Graph metamodel
resource = rset.get_resource(URI('my/path/mymodel.xmi'))  # assuming mymodel is located at 'my/path'
graph = resource.contents[0]  # you got your model root
graph.name  # Gets the graph name
graph.nodes  # Gets the contained nodes contained in the graph
graph.nodes[0].name  # Gets the name of the first node of the graph
graph.nodes[0].relatives  # Gets the relative nodes of the first node of the graph
```

If you don't know every metaclass attribute/references, you can use the `dir(...)` function to get them:

```Python
dir(graph)  # returns "[name, nodes]"
dir(graph.nodes[0])  # returns "[name, relatives, references]"
```

You can also get the element contained in a node (regardless of the metareference they are contained in), using `eContents`, and you can recursively get all the elements contained in an element using `eAllContents()`

```Python
graph.eContents  # Gets the element directly contained by "graph"

# This will print all the element directly or transitively contained in the "graph"
for element in graph.eAllContents():
    print(element)

```
