### ISSUE TITLE
AttributeError in new version 0.8.0

### ISSUE THREAD

**Issue by suntao2012** [pyecore/pyecore#24]
hi aranega,
when I use the version 0.7.16, create notation tree and save to file, it runs well; when I changed nothing but updated the version to 0.8.0, I met an error like this when I save to file. 

```
Traceback (most recent call last):
  File "usecase.py", line 28, in <module>
    resource.save(options={XMIOptions.SERIALIZE_DEFAULT_VALUES: True})
  File "/home/suntao/PY3ENV/local/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 323, in save
    tmp_xmi_root = self._go_across(root, serialize_default)
  File "/home/suntao/PY3ENV/local/lib/python3.4/site-packages/pyecore/resources/xmi.py", line 428, in _go_across
    frag, is_crossref = self._build_path_from(value)
  File "/home/suntao/PY3ENV/local/lib/python3.4/site-packages/pyecore/resources/resource.py", line 426, in _build_path_from
    uri_fragment = obj._xmiid
AttributeError: 'Structure' object has no attribute '_xmiid'

```

do you know what's wrong with that. if the problem isn't clear please let me know.

**Comment by aranega** [comment]
@suntao2012 My bad, this came from a missed merge between the "hotfixes" I performed for the 0.7.15/16  version and the 0.8.0 version. I fix this and I add new tests case right away. 
I'm very sorry about this...

**Comment by aranega** [comment]
@suntao2012 A new version, 0.8.1 is released on pypi for `pyecore` (and `pyecore-py2`)  with a fix and tests for your case. 
Once again, I'm so sorry about this... I'm working on the improvement of my tests cases.

**Comment by suntao2012** [comment]
@aranega 
thank you for your new version, it runs well. : )
