### ISSUE TITLE
ImportError while using Python setup.py install

### ISSUE THREAD

**Issue by shreyamdg** [pyecore/pyecore#27]
Hi, 

I was trying to install pyecore and I am using python34. I tried to use "python setup.py install" but it throws this error:

`python setup.py install`
`Traceback (most recent call last):`
`  File "setup.py", line 4, in <module>`
`    from setuptools import setup`
`ImportError: cannot import name 'setup'`

I tried to look around this issue and found this : https://pypi.org/project/ez_setup/

I tried to install ez_setup but issue: 

`$ pip install ez_setup`
`Traceback (most recent call last):`
`  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main`
`    "__main__", mod_spec)`
`  File "C:\Python34\lib\runpy.py", line 86, in _run_code`
`    exec(code, run_globals)`
`  File "C:\Python34\Scripts\pip.exe\__main__.py", line 5, in <module>`
`ImportError: cannot import name 'main'`

I even tried "$ pip install pyecore" which throws same: 

`$ pip install ez_setup`
`Traceback (most recent call last):`
`  File "C:\Python34\lib\runpy.py", line 171, in _run_module_as_main`
`    "__main__", mod_spec)`
`  File "C:\Python34\lib\runpy.py", line 86, in _run_code`
`    exec(code, run_globals)`
`  File "C:\Python34\Scripts\pip.exe\__main__.py", line 5, in <module>`
`ImportError: cannot import name 'main'`

**Comment by aranega** [comment]
Hi @shreyamdg 

The `setup.py` package uses `setuptools`, perhaps you misse this package in your system, try a `pip install setuptools -U` before trying the `python setup.py install` to see if it fixes the issue.

Also, if you are using pip, you can directly execute:

    pip install pyecore

Or, if you want to easily install it, and if you want to install it from the sources instead of getting it from `pypi`, you can also try:

    pip install -e .
 
Tell me if there is a solution that works better for you or if you still have the issue anyway.

**Comment by aranega** [comment]
@shreyamdg I must say, I never had to deal with `pip` behind a proxy. From what I found you could try to set the env variable `HTTP_PROXY` or `HTTPS_PROXY`

```bash
$ export HTTP_PROXY=http://proxy.server.com:8080  # for http proxy, otherwise use HTTPS_PROXY
$ pip install -e .  # in the 'pyecore' repository
```
If this solution works for you, you could write the `HTTP_PROXY=...` into your `.bashrc` (or the equivalent that exists in the linux subsystem in window if that's what you are using).

I also found more information about pypi behind a proxy [here](https://gist.github.com/jtrive84/48f0f8d3ca24db053b0daf4142fc8f8a), I hope this could help you.

**Comment by shreyamdg** [comment]
@aranega Your .bashrc suggestion worked! Thank you so much for your help. Closing this issue!
