### ISSUE TITLE
customizable resource URI

### ISSUE THREAD

**Issue by CFAndy** [pyecore/pyecore#33]
@aranega 
do you think we can add customizable uri for the href in xmi 
for example
```xml
<element xsi:type="domain:component" href="copy://_H4Ai4JDiEeiB-JBBIoiN_w/HWDemo2/test/level2_function.mdl#__yYxgJDfEeiB-JBBIoiN_w"/>
```
Here, I used "copy" prefix as a special hint for other purpose and _H4Ai4JDiEeiB-JBBIoiN_w is a UUID for compiler. 
the only valid resource uri is "./HWDemo2/test/level2_function.mdl"
The existing EProxy logic in pyecore will mess this totally up and fail to load right resource. 
Could you give me some hint on how to make it work with minor modificatoin on the pyecore code. I can add a dynmic patch locally as we are using python.  
Thanks!
-Andy

**Comment by aranega** [comment]
Hi @CFAndy 

Indeed, out of the box, the way the uri resolving is performed does not allow such URI format. Currently, there is a way of registering a new decoder to deal with such URI, but it implies that all the required resources are loaded first in the same `ResourceSet` (the resource auto-load current implementation cannot handle to auto-load it). 
Do you need to only deserialize data or to also serialize them back with the same URI format (meaning that each `Resource` should have a special UUID)?

Also, is the URI used to load the resource `copy://UUID/path/to/file` or simply `path/to/file`?

Regarding your 'constraints' the solution could be either a dedicated URI decoder or a dedicated `Resource` with a special URI (but the resource UUID could be an issue later, it depends on so many parameters).

As example, here is the code I used to deal with such `URI`, considering that all the resources (`a.xmi` and `b.xmi`) would have been loaded first using their path as URI:

```python
from  pyecore.resource import Resource

class SpecialDecoder(object):
    @staticmethod
    def remove_begining(path):
        path = path.replace('copy://', '')
        path = '/'.join(path.split('/')[1:])
        return path

    @classmethod
    def can_resolve(self, path, from_resource):
        if not path.startswith('copy://'):
            return False
        path = self.remove_begining(path)
        return from_resource.resource_set.can_resolve(path, from_resource)  # we use the resource set decoder

    @classmethod
    def resolve(cls, path, from_resource):
        path = cls.remove_begining(path)
        return from_resource.resource_set.resolve(path, from_resource)  # we use the resource set decoder


Resource._decoders.insert(0, CopyDecoder)  # we register the new decoder as first in the _decoders list
```

**Comment by aranega** [comment]
@CFAndy Got it! In this context, I suppose that a dedicated resource/URI should be better.

The only questions remaining so I can propose something is: 

* how the resource UUID is set the first time? 
* Let say you create a resource for a file 'test.xmi', how do you set the UUID at this point? 
* Also, is the format always `copy://UUID/path#fragment`?
* If you already have two resources `a.xmi` and `b.xmi`, when you load the two resources, how the resource UUID is determined? (if `a.xmi` reference `b.xmi`, I could extract the UUID from the href, but how the UUID is found for `a.xmi`?)

Sorry for all the questions, but they will lead me to the best way of solving this.

**Comment by CFAndy** [comment]
@aranega 

3. - Also, is the format always copy://UUID/path#fragment?
Yes. 
1. - how the resource UUID is set the first time
I'm not clear about the detail logic in legacy code. But we can assume it's a fixed random number for a existing *.xmi file.    
2. - Let say you create a resource for a file 'test.xmi', how do you set the UUID at this point?
same as question 1. 
4. - If you already have two resources a.xmi and b.xmi, when you load the two resources, how the resource UUID is determined? (if a.xmi reference b.xmi, I could extract the UUID from the href, but how the UUID is found for a.xmi?)
In my current project. there must be a c.xmi which refer a.xmi and provides the UUID of a.xmi. c.xmi will be directly load from the file system.

**Comment by aranega** [comment]
@CFAndy I pushed a new PyEcore version with some modification over the decoding parts. I checked the code of the custom `Resource` and `Decoder` from [the previous post](https://github.com/pyecore/pyecore/issues/33#issuecomment-408381804) and everything should still work.

**Comment by CFAndy** [comment]
Hi Vincent, 
  I got a chance to replace all my monkey-patched code with customized URI, Decoder and Resource, as you change the auto_resolve API. It works great. 
  As customized Resource should always implement _try_resource_autoload, would it be possible to make it a external and stable API?
-Andy

**Comment by aranega** [comment]
Hi @CFAndy 
I'm glad the custom resource works for you. By making the `_try_resource_autoload` an external API, is something like the `Decoder` component would do the trick?

**Comment by CFAndy** [comment]
Hi Vincent, 
 The exsiting API is great. I made the suggestion just because following case:
```python
    def _try_resource_autoload(self, uri, original_uri):
        try:
            rset = self.resource_set
            external_uri = URI(self.uri.apply_relative_from_me(uri)) 
            #I want to replace URI with my customized URI subclass. So I choose to override this function. 
            resource = rset.get_resource(external_uri)
            if uri != original_uri:
                rset.resources[original_uri] = resource
            return rset
        except Exception:
            raise TypeError('Resource "{0}" cannot be resolved'
                            .format(uri))
```
Do you think if there's another approch do that.  
-Andy

**Comment by aranega** [comment]
This issue is covered by #69 and a new version fixing it had been deployed ;)
