### ISSUE TITLE
TypeError for containers

### ISSUE THREAD

**Issue by rettenbs** [pyecore/pyecore#38]
Hi,

I tried the to run the code from the [quickstart](https://github.com/pyecore/pyecore/blob/master/doc/source/user/quickstart.rst#navigating-in-a-model):

```python
from pyecore.ecore import EClass, EReference

A = EClass('A')
A.eStructuralFeatures.append(EReference('cont1', containment=True, upper=-1))

a1 = A()
a2 = A()
a1.cont1.append(a2)
```

But I get the following error:
```
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pyecore\valuecontainer.py", line 290, in append
    self.add(value, update_opposite)
  File "C:\Program Files\Python36\lib\site-packages\pyecore\valuecontainer.py", line 293, in add
    self.check(value)
  File "C:\Program Files\Python36\lib\site-packages\pyecore\valuecontainer.py", line 46, in check
    if not EcoreUtils.isinstance(value, self.feature.eType):
  File "C:\Program Files\Python36\lib\site-packages\pyecore\valuecontainer.py", line 21, in isinstance
    elif isinstance(obj, _type):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

Sebastian

**Comment by rettenbs** [comment]
The code works, if you replace
```python
A.eStructuralFeatures.append(EReference('cont1', containment=True, upper=-1))
```
with
```python
A.eStructuralFeatures.append(EReference('cont1', eType=A, containment=True, upper=-1))
```

However, pyecoregen does not add the the additional ``eType`` parameter in the call. Hence, we cannot use the code generated by pyecoregen.

**Comment by aranega** [comment]
@rettenbs Thanks for the report! That's a missing statement in the documentation, indeed, the correct code would be as you wrote:

```python
A.eStructuralFeatures.append(EReference('cont1', eType=A, containment=True, upper=-1))
```
I will change the documentation asap!

Regarding pyecoregen, it should generate these statements in the `__init__.py` file in the generated package and not in the 'submodule'. This is mandatory to deal with forward references in types. Could you check if the `__init__.py` file contains the `eType` references? Perhaps there was a regression on the latest pyecoregen release that we missed.

**Comment by rettenbs** [comment]
Thank you for the information. We directly imported the model and not the Python module. Hence, the eType was not set. Works for us now.

**Comment by aranega** [comment]
@rettenbs Great! I'm relieved I don't have to code a new test case ;). Thanks again for the report, I will also go through all the documentation to check if everything is ok.
