### ISSUE TITLE
References in model instances are not found

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#40]
In my Ecore model, I defined the 'id' attribute as ID in EMF. When referencing to another element in my instance, it cannot find the id of the element as it does not use xmi:id (I use an XMLResource in EMF instead of an XMIResource) or uuid-attribute. Why is pyEcore not checking if an element has an ID-field defined and use that, since it supports defining an attribute as an ID? 
Or did I configure something wrong?

**Comment by aranega** [comment]
Hi @ewoudwerkman 

Indeed, the pyecore id reference only uses `xmi:id` for XMI Resources as it cannot automatically discover the attribute in the XML/XMI that would be used (`id` could be an attribute from your metamodel and not a technical attribute). Automatic detection would be a little bit risky for the XMI resource. 

Currently, the only way of changing the behavior is by modifying the code (the conditions that handle this case are at line 111 and 255 in `xmi.py`). Unfortunately, at the moment, there is no easy way to patch it without touching the code. Well... I guess a way of doing it currently, without touching the existing code would be to create a new Resource called `IDResource` that would have the following code:

```python
from pyecore.ecore import *
from pyecore.resources.xmi import XMIResource
from pyecore.resources import ResourceSet


class IDResource(XMIResource):
    def _init_modelroot(self, xmlroot):
        modelroot = super()._init_modelroot(xmlroot)
        id_value = xmlroot.get('id')
        if id_value is not None:
            self.use_uuid = True
            modelroot._internal_id = id_value
            self.uuid_dict[id_value] = modelroot
        return modelroot

    def _decode_attribute(self, owner, key, value):
        if key == 'id':
            owner._internal_id = value
            self.uuid_dict[value] = owner
        else:
            return super()._decode_attribute(owner, key, value)



rset = ResourceSet()
rset.resource_factory['xml'] = IDResource  # regitering the new resource for 'xml' extensions
rset.get_resource('B.xml')  # load the model
```

This code seems to work (I didn't test all corner cases), the model should load, but the serialization would still add `xmi:id` instead of `id`. I'm aware that it is not the best solution...

Actually, I partially implemented a mechanism to override `xmi:id` for XMI resources, but I didn't branch it properly... I will add it for the next release! Really sorry about the inconvenience...

**Comment by aranega** [comment]
@ewoudwerkman By re-reading your message, I sense that I probably misunderstood it. 

I thought that you meant you have an XMI(L) model with `id` attribute on each elements nodes that is used to give a technical id to the element instead of the traditionnal `xmi:id`. 

But, perhaps you meant that you added, in your `.ecore` metamodel, an `id` `EAttribute` on one of your elements (perhaps all your elements) with the `ID` property of this `EAttribute` set to `true`, and you want this attribute to be the one used as technical uuid instead of `xmi:id` when serializing/deserializing your models?

**Comment by ewoudwerkman** [comment]
@aranega, thanks for your prompt reply!

The latter is indeed the case: an ```EAttribute``` with the ```ID``` property set to ```true``` and use that attribute value for referencing. 

As you already identified, not all our classes have an id attribute in the model.

Any thoughts on how to solve this?

**Comment by aranega** [comment]
@ewoudwerkman I'm really sorry about the long time I took to release a new version and to release a solution for you issue, but I just released a new PyEcore version with support for `EAttribute` with their `iD` set to `True`. 

It works well on my tests cases and experiment I performed, but we all know how it works ;). Could you tell me if this new version works for you?

**Comment by ewoudwerkman** [comment]
Hi @aranega 

No need to be sorry, thanks for the effort! Later this week I've time to check the new version and get back to you if it works! Thanks!

**Comment by aranega** [comment]
Hi @ewoudwerkman
I don't think you did something wrong, it looks like an issue on the PyEcore side, there is definitely something I miscalculated (probably the `0..*` relationship). I check this on your model, test/patch/release asap! 
Thanks a lot for the test case and your patience.

**Comment by aranega** [comment]
@ewoudwerkman Victory! I have finally understand from where the issue come. Actually, the fault is located at this line:

```python
resource.contents.append(es)  # .contents should not be directly handled when roots are added to the resource instead:
resource.append(es)  # must be used
```

The thing is that you should always add roots to your resources using `.append` directly on the resource.  At this point, even if the element is added to the resource, the element does not see it. When it computes the references to serialize, the resource then considers that the element is out of any resource and thus, it does not serialize it. Modifying the line did the trick! It works on my side, but could you confirm this also works for you?

I know, this is not very logical regarding the fact that currently, you need to perform a `.contents[0]` if you want to get the first root of the resource.
Now, this is definitely an API fail on my side, I wanted to keep the almost same structure than EMF-Java, but at the end, I felt that it was more logical to consider the `Resource` as a list. I let the two abstractions mixed together which is not good, I will change that in the future (i.e: letting the `.contents` for retrocompatibility, but providing a full list protocol implementation for the `Resource` and change everything in the documentation). This way, it will avoid this case in the future.

Also, I took the liberty to propose you a 'simplified' version of the code you sent in the issue (I hope you don't mind, this is just some "tricks" that are not documented):

```python
from pyecore.resources import ResourceSet
from esdl import *
import esdl  # we directly import the generated metamodel as I understood that you generated the metamodel code

rset = ResourceSet()
print('Namespace: {}'.format(esdl.nsURI))
rset.metamodel_registry[esdl.nsURI] = esdl  # We can directly use it to register it in the metamodel registry

# By default, each extension that PyEcore does not know, it binds it to an XMIResource, so registration is not necessary

es = EnergySystem(name="test")
es.instance.append(Instance(name="test instance"))
es.instance[0].area = Area(name="test area")
pvparc = PVParc(name="PV parc")
ed = ElectricityDemand(name="E demand")
es.instance[0].area.asset.append(pvparc)
es.instance[0].area.asset.append(ed)
inPort = InPort(id='InPort1')
ed.port.append(inPort)
outPort = OutPort(id='OutPort1')  # you could also use: 'OutPort(id='OutPort1', connectedTo=[inPort])
pvparc.port.append(outPort)
outPort.connectedTo.append(inPort)
# inPort.connectedTo.append(outPort)  # as 'connectedTo' is a bidirectionnal relationship, no need to set it explicitaly
# I suppose you set it to be sure that the issue was not coming from this point.

print("Energy system(name={}), {}".format(es.name, dir(es)))
print("OutPort connectedTo: {}".format(outPort.connectedTo))
print("InPort connectedTo: {}".format(inPort.connectedTo))
resource = rset.create_resource('test.esdl')  # URI is not mandatory here, it is created direcly if a string is passed ;)
resource.append(es)  # need to use directly '.append' on the resource
resource.save()
```

Also, I saw that you used an `HttpURI` to load the metamodel from a remote url, and that you used `pyecoregen` to generate the metamodel code. Actually, `pyecoregen` automatically detect remote url, so, using the command line tool, you could direcly set the url as `-e` parameter. And if you want, you can check the [python-setuptools](https://github.com/pyecore/setuptools-pyecore/) tool built by @ferraith that let you interface `pyecoregen` in your `setup.py`. This is very handy if you metamodel moves often as it give you the ability to get a new version very quickly!

**Comment by ewoudwerkman** [comment]
Hi @aranega 
Yes! That did the trick, my references are shown correctly!
As you are completely right I mixed up the EMF API and the pyEcore API (or: did not carefully read it). Updating this API will for sure reduce errors by others.

Thanks for the proposals you mentioned, this cleans up the code nicely. 
I've progressed a little bit with the code and published it in a gitbook here: https://energytransition.gitbook.io/esdl/tooling-for-esdl/using-esdl-in-models/integration-with-python-and-pyecore, so others using our esdl.ecore model can use it to integrate it in their Python application.

As you can see (at the end of the page), I run into one small issue that we internally now use XMLResource for our Eclipse plugins, which don't like to see an xmi:version attribute in the root object. That's why I created an XMLResource based on your XMIResource, but without serializing the XMI URI and the xmi:version attribute. I did not dive into the semantic differences between XMLResource and XMIResource as this approach gets it working correctly in my use cases. Such an XMLResource might also be an addition to your supported resource implementations?

Thanks again for your effort, as I think that this approach works better than our current approach using ```generateDS``` to generate python classes of the XSD schema (that is generated from the ecore model)

**Comment by aranega** [comment]
Hi @ewoudwerkman 
I'm really glad it works for you! Indeed, I really need to update the API...

Thanks a lot for the kind words, this is really great that PyEcore can be helpful and I'm happy that you find in it a better solution than using `generateDS`. `generateDS` seems like a very powerful tool, but in the EMF/Ecore case, I got the impression that it introduces too much distance between the two worlds.

Thanks for the pointer towards the documentation, I quickly checked and I'm really impressed with all you did with ESDL and what you experimented with PyEcore (I like the small `attr_to_dict` you wrote)! Also, I forgot to mention that, but if you deal often with the generated Python code, you can try the `--auto-register-package` option that avoids you to manually register the metamodel in the metamodel registry of your `ResourceSet` (it registers it in the global metamodel registry).

I'm always happy to have contributions and surely, an `XMLResource` would be great! I don't know either what's the semantic difference between XML and XMI resources. I almost always worked with XML resources. Perhaps not so much at the end? Looking at your code for the`XMLResource`, perhaps the `XMIResource` requires a kind of "hook" just before the XML tree serialization. This would also give you, or other people,  the ability to easily go accross/modify the tree at the right time what do you think?

**Comment by ewoudwerkman** [comment]
Thanks for the feedback. It would be nice to add XMLResource to this project. My XMLResource is nothing more than an XMIResource and removing the XMI stuff...
