### ISSUE TITLE
Dealing with python reserved keywords as attributes in the metamodel

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#45]
Hi all,

In our metamodel there is an EAttribute named ```from```. To deal with this reserved keyword in Python, PyEcore converts this to ```from_```. Unfortunately it will also serialize to ```from_``` in the instance. How can we serialize this to ```from``` again?

The model is available here [https://github.com/EnergyTransition/ESDL/raw/master/esdl/model/esdl.ecore](https://github.com/EnergyTransition/ESDL/raw/master/esdl/model/esdl.ecore). Feature ```ProfileElement``` has the ```from``` attribute and is causing the issue.

**Comment by aranega** [comment]
Hi @ewoudwerkman,

The issue you have is a little bit connected to this one #29 . Currently, there is no automatic solution for this, but brainstorming without considering `EAnnotation` (which is the issue in #29 the solution I have are still ugly), I found a light way of patching the code for this. 

I suppose that you have generated the code of your metamodel here:

```python
import esdl

esdl.ProfileElement.from_.name = 'from'   # this will change the name in memory of the EAttribute
setattr(esdl.ProfileElement, 'from', esdl.ProfileElement.from_)  # this will ensure that the ProfileElement instance dict will have the required reserved word to deal with
```  

I made a quick test and it works (reading and writing):

```python
import esdl
from pyecore.resources import ResourceSet
from datetime import datetime

# We patch the code
esdl.ProfileElement.from_.name = 'from'
setattr(esdl.ProfileElement, 'from', esdl.ProfileElement.from_)

# we create a dummy model
root = esdl.ProfileElement()
root.from_ = datetime.now()

# we serialize it
rset = ResourceSet()
resource = rset.create_resource('test.xmi')
resource.append(root)
resource.save()

# we open it again in a new resource set just to be sure that the old resource is not took
rset = ResourceSet()
rset.metamodel_registry[esdl.nsURI] = esdl
root = rset.get_resource('test.xmi').contents[0]
print(root.from_)  # prints the good serialized time
```

The patch code could be added in the generated `__init__.py` directly towards the end of the file.

**Comment by ewoudwerkman** [comment]
Thanks for your quick reply! This patch will help us to continue our efforts!

**Comment by ewoudwerkman** [comment]
Would such a patch also work for the dynamic variant? I tried but I failed... ;-)

**Comment by aranega** [comment]
@ewoudwerkman Indeed, there is a way of patching the dynamic variant, which is a little bit different, but this is mainly the same idea. The thing is that this time, you don't directly handle the Python class that refelcts the `EClass` instance, but instead, your entry point is directly the `EClass` instance. Also, in the dynamic version, PyEcore does not rename the feature name, so this time, it is not a matter of adding the original name in the Python class, but more to add the "safe" name in the Python class.
I give you a version using the `DynamicEPackage` as I saw that you are using it in your documentation:

```python
from pyecore.resources import ResourceSet
from pyecore.resources.resource import HttpURI
from pyecore.utils import DynamicEPackage
from datetime import datetime

# we get the metamodel from the remote upstream URL
rset = ResourceSet()
mm = rset.get_resource(HttpURI('https://raw.githubusercontent.com/EnergyTransition/ESDL/master/esdl/model/esdl.ecore')).contents[0]

# Version with a DynamicEPackage
pack = DynamicEPackage(mm)
from_attribute = pack.ProfileElement.findEStructuralFeature('from')  # we get the feature that we want to inject
pack.ProfileElement.python_class.from_ = from_attribute  # we add it under a new attribute in the Python class that reflects the EClass

# We create an instance of ProfileElement
p = pack.ProfileElement(from_=datetime.now())
# or
# p = pack.ProfileElement()
# p.from_ = datetime.now()

# we serialize the model
resource = rset.create_resource('yyy.xmi')
resource.append(p)
resource.save()

# we reopen it with a different ResourceSet
rset = ResourceSet()
rset.metamodel_registry[mm.nsURI] = mm
model = rset.get_resource('yyy.xmi').contents[0]
print(model.from_)
```

I know this is a little cumbersome, but this is the only solution I have right now... I will see how to add a new util function that can do this nicely wether you are in a dynamic or a static mode.

**Comment by ewoudwerkman** [comment]
@aranega
Thanks for the example. I forgot to query the ProfileElement for the StructuralFeature (I tried to assign it directly). 
It doesn't matter that it's a little cumbersome, I see it as a part of the setup for Python. Thanks for mading EMF work on python!

**Comment by aranega** [comment]
I will try to add a special function somewhere in order to be able to add 'aliases' in classes (for dynamic and static ones'. Anyway, I will add something in the documentation about that and probably add a modification of the code generator. I will close the issue when everything will be in the framework.

**Comment by aranega** [comment]
@ewoudwerkman I added a special function to deal with aliases that can be used to deal with reserved keyword. I just saw that I failed for this section in the documentation. Here is the code that was presented as example:

```python
from pyecore.ecore import EClass, EAttribute, EString
from pyecore.utils import alias

@EMetaclass
class A(object):
  name = EAttribute(eType=EString)


alias('surname', A.name)

instance = A()
instance.name = 'myName'
assert instance.surname == instance.name
```

This should ease the setup process for your metamodel

**Comment by ewoudwerkman** [comment]
@aranega, thanks for the improvement!
I think we can close this issue now?

**Comment by aranega** [comment]
@ewoudwerkman Cool :) ! I close it!
