### ISSUE TITLE
 install_issubclass_patch conflict with typing.py's check

### ISSUE THREAD

**Issue by CFAndy** [pyecore/pyecore#47]
Hi Vincent @aranega 
  install_issubclass_patch patches the bulitin.issubclass . But typing code will validate the package name of your patched function, like following code for GenericType: 
```python
    def __subclasscheck__(self, cls):
        if self.__origin__ is not None:
            if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
                raise TypeError("Parameterized generics cannot be used with class "
                                "or instance checks")
            return False
        if self is Generic:
            raise TypeError("Class %r cannot be used with class "
                            "or instance checks" % self)
        return super().__subclasscheck__(cls)
```
Is there a way to solve this conflict?
-Andy

**Comment by aranega** [comment]
Hi @CFAndy !

Arf, I was expecting that something like that would cause issue at some point... Really sorry about that, I should be more careful... I do have a solution, but it would requires a modification of the `install_issubclass_patch` function (small one). The idea would be to add a new context manager to temp. switch on the original `issubclass` method. The modification of the `install_issubclass_patch` method would be like this:

```python
def install_issubclass_patch():
    old_issubclass = builtins.issubclass

    def pyecore_issubclass(self, cls):
        if isinstance(self, EClass):
            return old_issubclass(self.python_class, cls)
        return old_issubclass(self, cls)
    pyecore_issubclass.original = old_issubclass   # Here is the added line, we store the original issubclass to use it later
    builtins.issubclass = pyecore_issubclass
```

Then, the context manager would be the following:

```python
class original_issubclass(object):
    def __init__(self):
        self.pyecore_issubclass = builtins.issubclass

    def __enter__(self):
        builtins.issubclass = self.pyecore_issubclass.original

    def __exit__(self, type, value, traceback):
        builtins.issubclass = self.pyecore_issubclass
```

And you could use it like this:

```python
def __subclasscheck__(self, cls):
    with original_issubclass():
        if self.__origin__ is not None:
            if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
                raise TypeError("Parameterized generics cannot be used with class "
                                "or instance checks")
            return False
        if self is Generic:
            raise TypeError("Class %r cannot be used with class "
                            "or instance checks" % self)
        return super().__subclasscheck__(cls)
```

I know again that it is not ideal, but for a quick solution, this is what I can propose to you. You could only modify the `install_issubclass_patch`, then put the `original_issubclass` somewhere and go back to the original `issubclass` method whenever you need to. If you have your own fork of PyEcore, you can direcly modify it, I will try to add this context manager and the small modification asap and to push a release very quickly, but if you are in an hurry, don't wait for it, go with your own fork modification.

**Comment by CFAndy** [comment]
Hi Vincent, 
  Thank you so much for your quick solution. 
  The solution is great actually.
  But the typing code I mentioned here is in python standard library[typing](https://github.com/python/typing/blob/master/src/typing.py#L1148), which is very difficult for me to do so after deployment. 
 Thanks!
-Andy

**Comment by CFAndy** [comment]
Hi Vincent, 
  I think your current implementation will only be impacted by typing module in python3.6 and older. In 3.7, it works fine. 
  I just migrate to 3.7 as a quick workaround and it won't block me right now. 
-Andy

**Comment by CFAndy** [comment]
Hi Vincent, 
  My error happens in django integration. But I can reproduce error with following code:

```python
from typing import Mapping
from pyecore import *
iterable = []
if isinstance(iterable, Mapping):
    print("")
```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32

$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    if isinstance(iterable, Mapping):
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\typing.py", line 1162, in __instancecheck__
    return issubclass(instance.__class__, self)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\site-packages\pyecore\utils.py", line 74, in pyecore_issubclass
    return old_issubclass(self, cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\typing.py", line 1154, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\abc.py", line 209, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\typing.py", line 884, in __extrahook__
    if issubclass(subclass, scls):
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\site-packages\pyecore\utils.py", line 74, in pyecore_issubclass
    return old_issubclass(self, cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\abc.py", line 228, in __subclasscheck__
    if issubclass(subclass, scls):
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\site-packages\pyecore\utils.py", line 74, in pyecore_issubclass
    return old_issubclass(self, cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\typing.py", line 1154, in __subclasscheck__
    return super().__subclasscheck__(cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\abc.py", line 228, in __subclasscheck__
    if issubclass(subclass, scls):
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\site-packages\pyecore\utils.py", line 74, in pyecore_issubclass
    return old_issubclass(self, cls)
  File "C:\Users\fchen7\AppData\Local\Continuum\anaconda3\envs\tensorflow-gpu\lib\typing.py", line 1148, in __subclasscheck__
    raise TypeError("Parameterized generics cannot be used with class "
TypeError: Parameterized generics cannot be used with class or instance checks

**Comment by aranega** [comment]
@CFAndy Great! Thanks a lot for the use case, I check this asap!

**Comment by aranega** [comment]
@CFAndy @bmjjr So, I checked more in details what could be the issue. And I suspect a bug in the Python's `typing` module for some Python version. The issue seems not here for Python 3.5 nor 3.7, but for some version in Python 3.6.

I reproduced the bug under Python 3.6 with a very minimal example, and without PyEcore. Here is the code:

```python
from typing import Mapping
import builtins


original_issubclass = builtins.issubclass


def my_issubclass(self, cls):
    return original_issubclass(self, cls)

builtins.issubclass = my_issubclass


iterable = []

if isinstance(iterable, Mapping):
    print("OK")
```

This code only wraps the `ìssublcass` function, withtout any additional code. From the tracing I made, at some point, Python tries to match the type with many subclasses it has registered in a dedicated cache in the `abc` module. At some point, it hits this line in the `typing` module (while checking if it can be instance of a `MutableMapping`):

```python
# line 1447
if sys._getframe(1).f_globals['__name__'] not in ['abc', 'functools']:
   # ...
``` 
Which triggers the exception. This line does not exist anymore in the new Python version. Currently, I still don't know how I could fix the issue or "cheat" as the code uses frames and global stuffs. I will try some nasty stuffs, but I'm worried it will mess up other things...

**Comment by aranega** [comment]
The last pyecore version get rid of the patch, so there is no more problem regardless of the used python version :)
