### ISSUE TITLE
Issue deserializing '' for eattribute

### ISSUE THREAD

**Issue by AnjoMan** [pyecore/pyecore#53]
I ran into this with some ecore data I generated out of Enterprise Architect.

An example of the ecore I'm trying to parse would be something like:

```xml
<eClassifiers 
      xsi:type="ecore:EClass"
      name="LineFault"
      eSuperTypes="#//IEC61970/Base/Faults/Fault">
  <eStructuralFeatures 
      xsi:type="ecore:EAttribute"
      eType="#//IEC61970/Base/Domain/Length"
      name="lengthFromTerminal1"
      lowerBound="0"
      upperBound="1"
      transient="false"
      derived="false"
      ordered="false"
      changeable="true"
      defaultValueLiteral="" />
</eClassifiers>
```

The key issue is that the value of `defaultValueLiteral` has been set to `""` by my ecore exporter, and when `pyecore` tries to deserialize this it fails because it expects there to be an integer:

```
Traceback (most recent call last):
  File "/home/alodder/Development/.virtualenvs/PyCIM/bin/pyecoregen", line 11, in <module>
    sys.exit(main())
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecoregen/cli.py", line 15, in main
    generate_from_cli(sys.argv[1:])  # nocover
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecoregen/cli.py", line 57, in generate_from_cli
    model = load_model(parsed_args.ecore_model)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecoregen/cli.py", line 88, in load_model
    resource = rset.get_resource(uri_implementation(ecore_model_path))
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/resource.py", line 86, in get_resource
    resource.load(options=options)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 60, in load
    self._decode_eobject(child, modelroot)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 169, in _decode_eobject
    self._decode_eobject(child, eobject)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 169, in _decode_eobject
    self._decode_eobject(child, eobject)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 169, in _decode_eobject
    self._decode_eobject(child, eobject)
  [Previous line repeated 1 more time]
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 153, in _decode_eobject
    self._decode_eattribute_value(eobject, eattribute, value, from_tag)
  File "/home/alodder/Development/.virtualenvs/PyCIM/lib/python3.6/site-packages/pyecore/resources/xmi.py", line 144, in _decode_eattribute_value
    val = eattribute.eType.from_string(value)
ValueError: invalid literal for int() with base 10: ''
```

The specific failure point is [here](https://github.com/pyecore/pyecore/blob/d8ef263e259dc0835806a15a21fc68f581ef27bf/pyecore/resources/xmi.py#L144).

I think this would be easy to fix and I'd be willing to contribute the work, but I don't know if what I'm experiencing is a bug or if it is expected behaviour and my ecore is just badly formed.

**Comment by AnjoMan** [comment]
Specifically, the fix I would propose is:

* catch `ValueError`
* if `value` is falsy, don't perform the attribute set operation
   `eobject.__setattr__(eattribute.name, val)`

But I would appreciate some feedback as to whether this would be considered surprising to other users.

**Comment by aranega** [comment]
Hi @AnjoMan

Thanks for the issue report! I see what happend here, and actually, here there is many fixes possibles.  I tried with a modified metamodel, but I don't have the issue when the metamodel is deserialized, but I have this issue when a model is deserialized instead. Could you send me your metamodel so I can reproduce the exact same issue?

The patch you propose would be a valid one, but you put the finger on the potential issue, it could be surprising for other users. I think there is several fixes that could be done:

1. Catching the exception as you propose. Indeed, it could perhaps be a problem for other users
1. Change the `EInt` deserialization routine (or other type related) in PyEcore
1. Patch the `EInt` deserialization for your case
1. Modify the exporter, but it could be tricky here (I suppose)

On my side, I will check what is the behavior of Java-EMF for that. If it doesn't fail, I will try to approach the same behavior. If it does, it could means that the exported `.ecore` is problematic, but I really think that the temporary patch on the `EInt` or on the datatype `Length` derives from could be a good solution.

**Comment by AnjoMan** [comment]
I like your solution of excepting the specific type, but my model has has a number of types - `int`, `string`, `enum`, `float`, `bool` etc.. that all have this characteristic; I'd have to patch a large number of them, which means it would probably end up being similar to solution 1 --- in which case I think it would make sense to be consistent across all types.

It seems to me that this is a bad serialization, because the idea of giving a literal value that doesn't match the type is kind of nonsensical.  But I'm not totally convinced that a user would want their program to crash for this. I'd still expect a crash if it was something like `defaultLiteralValue="true"` and the type is e.g. a float. but in the case of an empty string we could be more forgiving.

Here is a minimal working example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
  xmi:version="2.0"
  xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  name="TC57CIM"
  nsPrefix="cim"
  nsURI="http://iec.ch/TC57/2013/CIM-schema-cim16#">
  <eSubpackages name="IEC61970">
    <eSubpackages name="Base">
      <eSubpackages name="Faults">
        <eClassifiers
          xsi:type="ecore:EClass"
          name="Fault"
          eSuperTypes="#//IEC61970/Base/Core/IdentifiedObject" />
        <eClassifiers
          xsi:type="ecore:EClass"
          name="LineFault"
          eSuperTypes="#//IEC61970/Base/Faults/Fault">
          <eStructuralFeatures
            xsi:type="ecore:EAttribute"
            eType="#//IEC61970/Base/Domain/Length"
            name="lengthFromTerminal1"
            lowerBound="0"
            upperBound="1"
            defaultValueLiteral=""
            transient="false"
            derived="false"
            ordered="false"
            changeable="true"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="Domain">
        <eClassifiers xsi:type="ecore:EClass" name="Length">
          <eStructuralFeatures
            xsi:type="ecore:EAttribute"
            eType="#//IEC61970/Base/Domain/UnitMultiplier"
            name="multiplier"
            lowerBound="0"
            upperBound="1"
            defaultValueLiteral=""
            transient="false"
            derived="false"
            ordered="false"
            changeable="true"/>
          <eStructuralFeatures
            xsi:type="ecore:EAttribute"
            eType="#//IEC61970/Base/Domain/UnitSymbol"
            name="unit"
            lowerBound="0"
            upperBound="1"
            defaultValueLiteral="m"
            transient="false"
            derived="false"
            ordered="false"
            changeable="false"/>
          <eStructuralFeatures
            xsi:type="ecore:EAttribute"
            eType="#//IEC61970/Base/Domain/Float"
            name="value"
            lowerBound="0"
            upperBound="1"
            defaultValueLiteral=""
            transient="false"
            derived="false"
            ordered="false"
            changeable="true"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="UnitMultiplier">
          <eLiterals name="m" value=""/>
          <eLiterals name="c" value=""/>
          <eLiterals name="k" value=""/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="UnitSymbol">
          <eLiterals name="VA" value=""/>
          <eLiterals name="W" value=""/>
          <eLiterals name="m" value=""/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Float"/>
      </eSubpackages>
      <eSubpackages name="Core">
        <eClassifiers xsi:type="ecore:EClass" name="IdentifiedObject" />
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>



```

**Comment by AnjoMan** [comment]
Ah. So I don't have control over the ecore exporter, its coming from an entriprise tool. It seems like what you are saying is that my ecore is not quite right. It sounds like the model-to-model transformation is what I would need. But right now I'm not really interested in writing a transformation on this model - I already have a dynamic package generator running off this ecore which is enough to maintain. So I think I should close this issue, since its not realy a problem with your package.

Thanks for your help! I really appreciate it!
