### ISSUE TITLE
PyEcore's XMI serialization of EDate is not compatible with EMF

### ISSUE THREAD

**Issue by stefanq** [pyecore/pyecore#54]
Hi, 

we have a C++ application (using emf4cpp) which interacts with models generated using PyEcore.
Unfortunately, when trying to open such an XMI we get errror mesages like
   Could not parse date string '2019-01-28 17:28:30.075312'.

The same would happen when reading such a model in Java:
According to  org.eclipse.emf.ecore.impl.EFactoryImpl the following serialization formats are supported by EMF:
```
protected static final DateFormat [] EDATE_FORMATS =
{
new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'.'SSSZ"),
new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'.'SSS"),
new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"),
new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm"),
new SafeSimpleDateFormat("yyyy-MM-dd")
};
```

In the XMI generated from Python attributes of type EDate get serialized in a format '%Y-%m-%d %H:%M:%S.%f'. Note that this lacks the 'T' between date and time which the supported formats expect.

A related issue is that instantiating pyecore.ecore.EDate (which internally is mapped to a datetime.datetime) from an ISO time is currently not possible:
```
date = EDate.from_string( datetime.now().isoformat() )
ValueError: time data '2019-01-29T09:50:55.370908' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

Thanks in advance

**Comment by aranega** [comment]
Hi @stefanq,

Thanks for your report and using PyEcore. You're right, it seems that PyEcore does not deserialize properly the string format classically used by EMF, I will change that for the next version! Meanwhile, I can propose this patch to you, which should do the trick:

```python
from datetime import datetime
from pyecore.ecore import EDate

EDate.from_string = lambda s: datetime.fromisoformat(s)
EDate.to_string = lambda d: d.isoformat()
```

This should allign PyEcore with EMF in your script. Sorry for the inconvenience, I will integrate this to the `develop` branch quickly!

**Comment by aranega** [comment]
@stefanq I pushed a fix on `develop` that works for Python 3.7 (using `fromisoformat`) and uses a loop over dedicated format for Python < 3.7. I will ship it with the next version :)

**Comment by stefanq** [comment]
Hello  Vincent,
thanks for the timely fix which also covers Python < 3.7 where datetime.fromisoformat() is not yet avaliable.
Unfortunately many current Linux distributions do not yet provide Python 3.7, hence the workaround is not applicable for us.
Therefore, seeing a 0.9.1 release as an official package available via PyPi will be welcome.
Is there any release date planned already?

Kind regards
Stefan

**Comment by aranega** [comment]
@stefanq Indeed, sorry about the proposal for the `datetime.fromisoformat()`, the Python version I have is up to date, I forgot the release schedule is very different from a distribution to another.

I think I will release a new version (0.10.0), very soon, probably in the week (perhaps today or tomorrow regarding a point I need to cover in the documentation). I was waiting having time to test more some features, but I will just let them in the code, without documentation.

**Comment by aranega** [comment]
@stefanq I just release a new version. Tell me if it works for you :)

**Comment by stefanq** [comment]
Hello Vincent,

I just gave our EMF model generating script another try (with PyEcore 0.10.2) and found that there seems to be no way to get an EDate serialized into XMI in the format EMF usually uses (which is ISO 8601 format (which is with a 'T' between date and time)).

I found that instantiating an EDate is possible with
`     object.modifiedDate = EDate.from_string( str( datetime.now() ) )
`
Note that any attempt to initialize EDate from an ISO 8601 string like in
`     object.modifiedDate = EDate.from_string( datetime.now().isoformat() )
`
will fail.

However, whatever format EDate.from_string() accepts is not that important, but the crucial point is that if an EDate gets serialized to XMI the format has to be EMF compliant so that further processing of XMIs generated by pyEcore will be possible with Eclipse tools (or emf4cpp).

Kind regards
Stefan

**Comment by aranega** [comment]
Hello Stefan,

That's strange, I don't have failure or problems using the last version ( `> 0.10.0`)
Here is the test code I used

```python
from pyecore.ecore import *
from pyecore.resources import *
from datetime import datetime

# Test serialization and deserialization
date = EDate.from_string('2019-01-28T17:28:30')
print(date)
print(EDate.to_string(EDate.from_string(datetime.now().isoformat())))

# Test serialization in XMI (creating first a simple metamodel)
nsPrefix = 'testexample'
nsURI = 'http://testexample'
eClass = EPackage(name='testExample', nsPrefix=nsPrefix, nsURI=nsURI)


@EMetaclass
class A(object):
    mydate = EAttribute(eType=EDate)


a = A()
a.mydate = datetime.now()

rset = ResourceSet()
resource =  rset.create_resource('XYZ.xmi')
resource.append(a)
resource.save()

# We force deserialize it again
rset  = ResourceSet()
rset.metamodel_registry[nsURI] = eClass
resource = rset.get_resource('XYZ.xmi')
print(resource.contents[0].mydate)
```

And here is the resulting XMI:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<testexample:A xmlns:testexample="http://testexample" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" mydate="2019-06-05T17:00:25.944137" xmi:version="2.0"/>
```
Perhaps you still have an old version of PyEcore in one of your configuration?

**Comment by stefanq** [comment]
Hi Vincent,

thanks for your quick response. I can confirm that your test code produces a XMI serialization with 'mydate' in ISO 6801 format (i.e. with 'T' as the delimiter). I'll go and check what makes the difference in my script (tomorrow).

Thanks
Stefan

**Comment by aranega** [comment]
Perhaps @ewoudwerkman has a point on what could be the problem see #64

**Comment by stefanq** [comment]
I found out that my model generating script does not use the pyEcore from installed in the system but instead an old version linked into the script directory.
After cleaning this up, the EDate serialization behaves as demonstrated by your test code.

Thanks again
Stefan
