### ISSUE TITLE
Saved XMI format has issues with non-containment references in Eclipse

### ISSUE THREAD

**Issue by annighoefer** [pyecore/pyecore#58]
Thanks for all the great work. I really appreciate this project. I found two minor issues when working with both, Eclipse and pyecore, which are easy to fix in my opinion:

1) When storing non-containment references an '@' seems missing before single element references. The stored XMI files cannot be opened in Eclipse EMF, because it always skips the first letter.

Temporary fix:
ecore.py -> eURIFragment() -> line 267: 
return '{0}/@{1}'.format(parent.eURIFragment(), name) #BA added '@' for being compatible to Eclipse

2) When using id attributes as references, it is not checked for malformed id values. E.g. a space in the id attribute’s value creates errors the next time the file is loaded because it looks like multiple references to be loaded (split at the spaces). However, none of the partial ids will exist. 

Temporary fix:
resource.py -> _build_path_from() -> line 521: 
if id_att_value is not None and ' ' not in id_att_value: #BA prevent ids with spaces from being used

**Comment by aranega** [comment]
Thanks a lot for the kind words and for having spotted these two bugs! I can't believe I didn't spot them before...

Your fixes sounds very good to me. I can fix everything, but if you prefer, you could create a PR with the fixes, I would be very happy to merge it in the `develop` branch for the next release :) (which should be released very soon as I will try to add some quick first performances fixes).
