### ISSUE TITLE
Missing timezone in datetime parser

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#64]
Hi @aranega,

I've found an issue in the datetime parsing when timezone information is included.
When you want to parse an ISO 8601-based date (e.g. from an XMI generated in Eclipse, such as 2014-01-01T00:00:00.000+0100 or 2014-01-01T00:00:00.000Z or 2014-01-01T00:00:00.000+01:00) the parser of pyEcore generates an error, because the supported formats do not contain timezone information, i.e. the UTC offset.

Look at ```innerutils.py``` at the end:
``` python
def parse_date(str_date):
    try:
        return datetime.fromisoformat(str_date)
    except Exception:
        formats = ('%Y-%m-%dT%H:%M:%S.%f',
                   '%Y-%m-%dT%H:%M:%S.%f',
                   '%Y-%m-%dT%H:%M:%S',
                   '%Y-%m-%dT%H:%M',
                   '%Y-%m-%d %H:%M:%S.%f',
                   '%Y-%m-%d %H:%M:%S.%f',
                   '%Y-%m-%d %H:%M:%S',
                   '%Y-%m-%d %H:%M',
                   '%Y-%m-%d',)
        for format in formats:
            with ignored(ValueError):
                return datetime.strptime(str_date, format)
raise ValueError('Date format is unknown')
```
The timezone directive is ```%z```, but is missing here. (Keep in mind that this directive is added in python 3). Furthermore the 2nd and 5th of ```formats``` is duplicated from the previous format, probably you intended to add the ```%z``` here?

**Comment by ewoudwerkman** [comment]
BTW, the fromisoformat() (peviously used in pyEcore) is not compliant with most ISO 8601 formats, so I think it is good to use these formats here.

**Comment by aranega** [comment]
Thanks a lot @ewoudwerkman for the tracking of the mistake. Indeed, I had probably duplicate the line to set the extra format (honestly, I don't recall for sure, but I know me and yes... I have probably forgot that... I need to improve the test set).

I will try to give your proposition a try as soon as I can, in the meantime, if you want to propose a PR, I would include it very soon.

**Comment by ewoudwerkman** [comment]
According to EMF's [EFactoryImpl](https://github.com/eclipse/emf/blob/master/plugins/org.eclipse.emf.ecore/src/org/eclipse/emf/ecore/impl/EFactoryImpl.java) a ```Date``` is parsed using the following formats: 
```java
 protected static final DateFormat [] EDATE_FORMATS = 
  {
    new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'.'SSSZ"),
    new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'.'SSS"),
    new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss"),
    new SafeSimpleDateFormat("yyyy-MM-dd'T'HH:mm"),
    new SafeSimpleDateFormat("yyyy-MM-dd")
};
```
Conversion back to string is using the first one:
```java
...
else if (objectValue.getClass() == Date.class)
    {
      return EDATE_FORMATS[0].format((Date)objectValue);
}
...
```
which means that it is including time zone information when serializing using the ```Z``` letter. According to the ```SimpleDateFormat``` [javadoc](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) of Java 7  ```Z``` means:

| Letter | Date or Time Component | Presentation | Examples |
| -- | -- | -- | -- |
| z | Time zone | General time zone | Pacific Standard Time; PST; GMT-08:00 |
| Z | Time zone | RFC 822 time zone | -0800 |
| X | Time zone | ISO 8601 time zone | -08; -0800;  -08:00 |

So the time zone is defined as UTC offset in hours and minutes *without* a colon in the middle (according to RFC 822). But RFC 822 also allows for a few timezones defined as strings such as "GMT" and "UT"... and RFC 822 is not the same as ISO 8601.

Starting from Java 7, it supports the ``X`` timezone modifier (instead of ```Z```), compatible with ISO 8601. So the best thing is to let EMF support this modifier, too, because then it is compatible with python's ```isoformat()```. This modifier, in the form of ```XXX``` (extended format) also renders the UTC offset as HH:mm, so with a colon, just like python.

In pyEcore it is serialized back to a string as follows:
```python
EDate = EDataType('EDate', datetime,
                  from_string=parse_date,
                  to_string=lambda d: d.isoformat())
```
So it is using ```datetime.isoformat()```. When there is no time zone information, it serializes without this information:
```python
print(datetime.now().isoformat())
```
output:
```
2019-06-06T09:36:38.536545
```
This is ok, because it can be parsed back by ```EDATE_FORMATS[1]``` when reading the file with this date.
But if there is time zone information available (e.g. input string in XMI is EMF-generated and like ```2019-06-06T09:36:38.536545+0200```), it will not work (I add the timezone here manually in the example):
```
print(datetime.now(tz=tzlocal()).isoformat())
2019-06-06T09:36:38.536545+02:00
```
It adds the (correct according to ISO 8601) colon between the hours and the minute of the UTC offset, but this is not allowed by EMF.
To fix this we need to use ```strftime()```:
```
print(datetime.now(tz=tzlocal()).strftime('%Y-%m-%dT%H:%M:%S.%f%z'))
2019-06-06T09:36:38.536545+0200
```
The latter one makes it (for now) compatible to the current (2.17) EMF version's ```EDATE_FORMATS[0]```
My suggestion is to make this the default for now. 
Bad side is that it always adds the fraction seconds, but this is necessary for when there is time zone information in the datetime object

**Comment by aranega** [comment]
@ewoudwerkman Wow! Thanks so much for all your efforts and your detailed explanation!

I agree, the fraction second part is not a problem especially if EMF understands it, better be compatible as much as we can. 

I saw your PR, I'll integrate it asap

**Comment by aranega** [comment]
@ewoudwerkman I finally released your PR, really sorry for the delay... and thank you again for your help!
