### ISSUE TITLE
Root EAttribute id is not stored in the uuid_dict of the resource

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#75]
Hi @aranega 

We ran into the issue when referring to the root resource' id (e.g. file.xml#myID) it cannot be found in the uuid_dict. Checking the code I found that the root node, when parsed, does not process feature.iD attribute of ecore, while (based on an earlier issue #40 ) attributes of child nodes do.

I created a patch to fix this problem.

**Comment by ewoudwerkman** [comment]
See #76 for the PR

**Comment by aranega** [comment]
Hi @ewoudwerkman, again, thanks a lot for your PR and your tickets. I will merge that right away and I'll perform a new release asap (closing another ticket at the same time).

**Comment by aranega** [comment]
A new version `0.11.2` is available with the fix you provided and the one that @annighoefer proposed. Thanks @ewoudwerkman @annighoefer!
