### ISSUE TITLE
A Model serialization error

### ISSUE THREAD

**Issue by stefanq** [pyecore/pyecore#77]
with the current pyecore release I see a model serialization error which I did not have with 0.9.x releases.I did some bisection across pyecore releases and by stripping down my model.Regarding the ecore releases I found that serialization is working with pyecore-0.11.1 but no longer with pyecore-0.11.2.Regarding the model element causing this I found, that this is due to a class Clock which has multiple EFeature with containment of another class Time. 

The class definition is as follows and the serialization error is in 
 _go_across() in resources/xmi.py (see the backtrace at the end).
The exception occurs because for some reason extraction of the feature 'period' yields a child None in _go_across(). In contrast to the other features of class Time the 'period' has a lower bound of 0 (but I don't know if the serialization of the other features of class Time would fail as well):

    <eClassifiers xsi:type="ecore:EClass" name="Clock" eSuperTypes="#//model/ModelObject #//model/TraceObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" eType="#//model/Frequency" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="period" ordered="false" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="drift" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="0">
        </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="range" ordered="false" lowerBound="1" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startTimeFixed" lowerBound="1" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTimeIsRandom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startTimeMin" lowerBound="1" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startTimeMax" lowerBound="1" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startValue" ordered="false" lowerBound="1" eType="#//model/Time" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1" eType="#//model/ClockUser" eOpposite="#//model/ClockUser/clock">
        </eStructuralFeatures>
    </eClassifiers>

```
Traceback (most recent call last):
  File "Python/exampleModel.py", line 107, in <module>
    MyModel( 2 ).save( './exampleModel.iprx' )
  File "/home/work/dev/s3/python/Python/inchron/__model.py", line 698, in save
    raise error
  File "/home/work/dev/s3/python/Python/inchron/__model.py", line 696, in save
    resource.save( options = { XMIOptions.SERIALIZE_DEFAULT_VALUES: True } )
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 355, in save
    tmp_xmi_root = self._go_across(root, serialize_default)
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 486, in _go_across
    node.append(self._go_across(child, serialize_default))
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 486, in _go_across
    node.append(self._go_across(child, serialize_default))
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 486, in _go_across
    node.append(self._go_across(child, serialize_default))
  [Previous line repeated 1 more time]
  File "/home/work/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 395, in _go_across
    eclass = obj.eClass
AttributeError: 'NoneType' object has no attribute 'eClass'
```

**Comment by aranega** [comment]
@stefanq Thanks for the issue report. I will try to reproduce the error and I check that right away. I have no idea why the serialization tries to deal with the `None` value and especially what could have introduce the issue in the commits. I'll check that right away!

**Comment by aranega** [comment]
Ok, I reproduced the bug, it comes from the fact that at some point, during your model manipulation, the  `period` feature must have been set to `None`. In that case, PyEcore store this information to be able to serialize a `nil` element (as refered in [this issue](https://github.com/pyecore/pyecore/issues/18#issuecomment-370955052)). I didn't covered the case where you enforce a `None` in the a containement feature.
I'll fix that and release a new version as this may block you otherwise.

**Comment by aranega** [comment]
@stefanq I released a new version with the fix ;), I hope I correctly found the root of the problem and that it will fix the issue you found.

**Comment by stefanq** [comment]
> Ok, I reproduced the bug, it comes from the fact that at some point, during your model manipulation, the `period` feature must have been set to `None`.

Your are exactly right, at some point when constructing my slightly complex model an already constructed Time instance somehow gets deconstructed again :-/
I.e. due to an error in my model generator it turned into a test case for a corner case of your serialization routine.

Thanks for responding on that so quickly!
