### ISSUE TITLE
Import failure for a metamodel, BadValueError importing uml2.ecore

### ISSUE THREAD

**Issue by marvingreenberg** [pyecore/pyecore#78]
I'm trying to import an EMF model,  using the PyPI python, pyecore.\_\_version\_\_ 0.11.3

    https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.uml/model/UML.ecore

This loads using the Java EMF implementation.  I first import (I just copied everything locally)

    https://git.eclipse.org/c/emf/org.eclipse.emf.git/plain/plugins/org.eclipse.emf.ecore/model/Ecore.ecore
    https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.types/model/Types.ecore

But when I import the uml2.ecore, I get

    _uml2 = rset.get_resource(URI('ecore/uml2.ecore'))
    (Pdb) n
    pyecore.valuecontainer.BadValueError: Expected type EBoolean(bool), 
    but got type str with value true instead for feature 
    <EAttribute abstract: EBoolean(bool)> of <EClass name="EClass">

I started putting in a little hack to have ```pyecore.valuecontainer.check()``` to coerce a ```str('true')``` to ```bool(True)``` for this case but figured I'd ask if there is some "proper" way to do this, or if I'm misunderstanding the problem.  I haven't traced this to a specific line in the uml2.ecore.

Here's exactly what I run (with the three ecore files in the ```ecore/``` directory)

    #!/usr/bin/env python3
    from pyecore.resources import ResourceSet, URI
    rset = ResourceSet()
    # Load ecore
    _ecore = rset.get_resource(URI('ecore/Ecore.ecore'))
    _types = rset.get_resource(URI('ecore/Types.ecore'))
    for metamodel in (_ecore, _types):
        metamodel_root = metamodel.contents[0]  # metamodel root package
        rset.metamodel_registry[metamodel_root.nsURI] = metamodel_root
    import pdb; pdb.set_trace()
    _uml2 = rset.get_resource(URI('ecore/uml2.ecore'))  # throws here

**Comment by marvingreenberg** [comment]
When I add the hack for boolean in check() it then fails analogously for int, with a BadValueError 

    pyecore.valuecontainer.BadValueError: Expected type EInt(int), 
    but got type str with value -1 instead for feature 
    <EAttribute upperBound: EInt(int)> of <EClass name="ETypedElement">

So it seems like this is a generic issue for the UML primitive types in the metamodel as XML strings.  Maybe I should read the docs for something about type converters or something...

**Comment by marvingreenberg** [comment]
Perhaps, https://pyecore.readthedocs.io/en/latest/user/quickstart.html#adding-external-metamodel-resources

I'll see if this will fix things.

**Comment by marvingreenberg** [comment]
OK, I'm just confused.  It seems like it should work.  I found this in ```pyecore/type/type.py```, and that seems to be an existing from_string converter for ```EBoolean(bool)``` in the ecore metamodel.

    Boolean = EDataType('Boolean', instanceClassName='boolean',
                    to_string=lambda x: str(x).lower(),
                    from_string=lambda x: x in ['True', 'true'])

I wrote a little function to augment one or another of the base metamodels with the _missing_ type conversions (before I found that).  And I changed the code to just load the ecore files directly from the internet, so this should just run...

    #!/usr/bin/env python3
    from pyecore.resources import Ecore, ResourceSet
    from pyecore.resources.resource import HttpURI
    import sys
    
    rset = ResourceSet()
    # Load ecore
    ecoreurl = 'https://git.eclipse.org/c/emf/org.eclipse.emf.git/plain/plugins/org.eclipse.emf.ecore/model/Ecore.ecore'
    typesurl = 'https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.types/model/Types.ecore'
    _ecore = rset.get_resource(HttpURI(ecoreurl))
    _types = rset.get_resource(HttpURI(typesurl))
    
    def augment(metamodel_root):
        to_bool = lambda x: x.lower() == 'true'
        from_bool = lambda x: str(x).lower()
        # augment the UML2 metamodel with some required type conversions
        datatypes = [
            Ecore.EDataType(*args, **kwargs)
            for args, kwargs in (
                (('String', str), {}),
                (('EInt', int, int), {}),
                (('EBoolean', bool, False), {
                'from_string': to_bool, 'to_string': from_bool}),
            )
        ]
        metamodel_root.eClassifiers.extend(datatypes)
    
        for c in metamodel_root.eClassifiers:
            print('Classifier {c}: fs:{fs}'.format(c=c, fs=getattr(c,'from_string',None)))
    
    
    # _ecore = rset.get_resource(URI('ecore/Ecore.ecore'))
    # _types = rset.get_resource(URI('ecore/Types.ecore'))
    
    _ecore_root = _ecore.contents[0]  # metamodel root package
    augment(_ecore_root)
    rset.metamodel_registry[_ecore_root.nsURI] = _ecore_root
    
    _types_root = _types.contents[0]  # metamodel root package
    
    rset.metamodel_registry[_types_root.nsURI] = _types_root
    
    try:
    #    _uml2 = rset.get_resource(HttpURI('ecore/uml2.ecore'))
        uml2url = 'https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.uml/model/UML.ecore'
        uml2 = rset.get_resource(HttpURI(uml2url))
    
    except Exception as e:
        print("load of uml2 metamodel failed: {} ".format(e))
        sys.exit(1)

When I run that, it fails the same way.  But what is interesting is the info augment prints when I augment the _ecore_root as shown here...

    % python3 load_model.py 
    Classifier <EClass name="EAttribute">: fs:None
    Classifier <EClass name="EAnnotation">: fs:None
    <snip... many classifiers... >
    Classifier EBoolean(bool): fs:<bound method EDataType.from_string of EBoolean(bool)>
    Classifier EBooleanObject(bool): fs:<bound method EDataType.from_string of EBooleanObject(bool)>
    <snip... many more ..>
    Classifier String(str): fs:<bound method EDataType.from_string of String(str)>
    Classifier EInt(int): fs:<bound method EDataType.from_string of EInt(int)>
    Classifier EBoolean(bool): fs:<function augment.<locals>.<lambda> at 0x10d8f68b0>
    load of uml2 metamodel failed: Expected type EBoolean(bool), but got type str with value true instead for feature <EAttribute abstract: EBoolean(bool)> of <EClass name="EClass"> 

Which seems like the EBoolean(bool) classifier is already part of _ecore_root before I add my three at the bottom, and the from_string method is the bit of code from ```pyecore/type/type.py``` which seems to be trying to do the right thing.

**Comment by aranega** [comment]
Hi @marvingreenberg thanks a lot for your ticket and trying to use PyEcore. As you saw, the UML metamodel deserialization is a tough part. The reason is that it references other metamodels on specific URI in it's XMI. Those specific URI needs to be register in the resource set, otherwise, the resolution cannot be properly made. In your case, you also bumped into the problem that occurs when `EAttribute` from a metamodel reference types from a dynamic metamodel and which requires to be deserialized (in your case, you loaded the Ecore metamodel in a dynamique way and the UML metamodel makes references to attributes of this metamodel). This latter issue can be easily covered by reusing the Ecore metamodel expressed in Pyecore. The first problem however (dedicated URI) needs to be covered by hand.

For the UML metamodel, you need to have the Ecore metamodel (provided by PyEcore), the UMLType metamodel (not really used for the UML metamodel deserialization, but is used for UML models serialization) and the UML metamodel in itself.

The receipe is the following:

1. you create a resource with the right dedicated URI for the Ecore metamodel
1. you place the Ecore metamodel inside
1. you load the UMLType metamodel
1. you create a resource with the right dedicated URI for the UMLType metamodel
1. you place the UMLType metamode inside
1. you patch all the types from UMLType to add dedicated serialization/deserialization capabilities
1. you load the UML metamodel
1. profit

Here is the code I used to do that (partially based on yours):

```python
from pyecore.resources import Ecore, ResourceSet
from pyecore.resources.resource import HttpURI
import pyecore.ecore as Ecore
from pyecore.utils import DynamicEPackage

rset = ResourceSet()

# register ecore at the right URI regarding UML.ecore references
ecore_resource = rset.create_resource('platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore')
ecore_resource.append(Ecore.eClass)

# Load type
typesurl = 'https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.types/model/Types.ecore'
_types = rset.get_resource(HttpURI(typesurl))

# register types at the right URI regarding UML.ecore references
type_resource = rset.create_resource('platform://plugin/org.eclipse.uml2.types/model/Types.ecore')
ecore_resource.append(_types.contents[0])

# Adding types conversion for types (not used for UML metamodel, but important for UML model instances)
uml_types = DynamicEPackage(_types.contents[0])
uml_types.String.from_string = Ecore.EString.from_string
uml_types.String.to_string = Ecore.EString.to_string
uml_types.Boolean.from_string = Ecore.EBoolean.from_string
uml_types.Boolean.to_string = Ecore.EBoolean.to_string
uml_types.Integer.from_string = Ecore.EInt.from_string
uml_types.Integer.to_string = Ecore.EInt.to_string
uml_types.UnlimitedNatural.from_string = Ecore.EInt.from_string
uml_types.UnlimitedNatural.to_string = Ecore.EInt.to_string
uml_types.Real.from_string = Ecore.EFloat.from_string
uml_types.Real.to_string = Ecore.EFloat.to_string


uml2url = 'https://git.eclipse.org/c/uml2/org.eclipse.uml2.git/plain/plugins/org.eclipse.uml2.uml/model/UML.ecore'
uml2 = rset.get_resource(HttpURI(uml2url))

uml2dyn = DynamicEPackage(uml2.contents[0])
print(uml2dyn.Classifier.name)
```

That's all. But really, if you want to use UML2, you can use the PyUML2 project that have been started (I really need time to continue to work on this...) https://github.com/pyecore/pyuml2
The project allows you to register the UML2 metamodel/load a model in an easier way:

```python
from pyecore.resources import ResourceSet
import pyuml2.uml as uml

rset = ResourceSet()
rset.metamodel_registry[uml.nsURI] = uml
resource = rset.get_resource('path/to/my/model.uml')
model = resource.contents[0]

print(model.name)
print(model.packagedElement)
print(model.nestedPackage)
```

**Comment by marvingreenberg** [comment]
OK, I've succeeded loading a single model using pyuml2 as you suggested.  I just stripped out the "profile" CDA from the model I tried - for now I don't know what its for.  I may try to patch pyuml2 to allow an option to elements that are in undefined namespaces or something.  Thanks again.
