### ISSUE TITLE
self-referential xmlns 

### ISSUE THREAD

**Issue by goretkin** [pyecore/pyecore#79]
I am trying to load this:
https://www.omg.org/spec/UML/20131001/UML.xmi

```python
resource = rset.get_resource(URI(uml_mm_path))
mm_root = resource.contents[0]
rset.metamodel_registry[mm_root.nsURI] = mm_root
```

but I get `KeyError: 'Unknown metamodel with uri: http://www.omg.org/spec/UML/20131001'`

Indeed, the first few lines of the UML.xmi file show:
```
<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/spec/XMI/20131001" xmlns:uml="http://www.omg.org/spec/UML/20131001" xmlns:mofext="http://www.omg.org/spec/MOF/20131001">
	<uml:Package xmi:type="uml:Package" xmi:id="_0" name="UML" URI="http://www.omg.org/spec/UML/20131001">
```

What's the right way to load this resource? What I am actually trying to do is load `http://www.omg.org/spec/MOF/20131001/emof.xmi` which is defined in this resource: https://www.omg.org/spec/MOF/20131001/MOF.xmi , which in turn cross-references the UML model.

**Comment by ewoudwerkman** [comment]
It seems that the these models use URIs that don't exist (i.e. you have to add ```UML.xmi``` to the URI to get to the correct file at OMG.org. 
Try downloading all these files to disk and replace the URIs that don't exist with the ones that do exist, e.g. replace
```http://www.omg.org/spec/UML/20131001``` with ```http://www.omg.org/spec/UML/20131001/UML.xmi``` in those files.

**Comment by goretkin** [comment]
Thanks, I see now that my question arose from of my misunderstanding of XML namespaces.
