### ISSUE TITLE
Cardinality many bug?

### ISSUE THREAD

**Issue by jorensips** [pyecore/pyecore#84]
I believe there is an error in the ecore.py file, in the ETypedElement class, _compute_many function. Here, the check upper - lower > 1 seems to be a mistake.

For example if I have a model of a graph, containing a node class and edge class, I would have a reference going from Edge to Node with cardinality 2..2. The current check would then result in many==false.

I might be overlooking something, but to me it seems the difference between upper and lower is irrelevant.

**Comment by aranega** [comment]
Hi @jorensips ,

Indeed, you're right, I made a quick assumption... that everyone uses mainly "0..*", "1..*" or "0..1", "1..1" relationships. I will fix that! However, as in EMF, PyEcore will not "generate" or enforce constraints over the number of elements at runtime withtout an explicit validation phase (as it can be problematic for "work in progress" models).
I try to do that ASAP, add some tests and release a new version, it will be good anyway, I need to find more time to work on future versions.

**Comment by aranega** [comment]
Hi @jorensips 
I released a new version with some bugfixes as well the bugfix of this issue :)
Thanks again for the issue!
