### ISSUE TITLE
Creating a new Object with EReference deletes data in other objects

### ISSUE THREAD

**Issue by filippomc** [pyecore/pyecore#86]
The behaviour is described in the following test (last test not passing):

```python
from pyecore.ecore import EObject, MetaEClass, EReference, EString


class MyObject(EObject, metaclass=MetaEClass):
    pass


class MyCollectorObject(EObject, metaclass=MetaEClass):
    referenced = EReference(eType=MyObject, ordered=True, unique=True, containment=True, upper=-1)


def test_reference_bug():
    objects = [MyObject(), MyObject()]
    o = MyCollectorObject()
    o.referenced.extend(objects)
    assert len(o.referenced) == 2
    o2 = MyCollectorObject()
    o2.referenced.extend(objects)
    assert len(o2.referenced) == 2
    assert len(o.referenced) == 2
```

```
=================================== FAILURES ===================================
______________________________ test_reference_bug ______________________________

    def test_reference_bug():
        objects = [MyObject(), MyObject()]
        o = MyCollectorObject()
        o.referenced.extend(objects)
        assert len(o.referenced) == 2
        o2 = MyCollectorObject()
        o2.referenced.extend(objects)
        assert len(o2.referenced) == 2
>       assert len(o.referenced) == 2
E       assert 0 == 2
E        +  where 0 = len([])
E        +    where [] = <tests.test_new.MyCollectorObject object at 0x7f703d1b5350>.referenced
```
So, after adding the same objects to `o2`, the objects are disappearing from `o`.

**Comment by aranega** [comment]
Hi @filippomc,

This behavior is normal, the reference `referenced` is `containment`, meaning it acts like a container. An object cannot be contained in two containers, only one at the time. Therefore, when you move the objects from one collection to the other, they are removed from the collection they were in. If you want the object to be in two collection, the regular pattern is to create a container somewhere, put the object inside and create an object that will represent the ref towards the real object. This way, you can create two ref objects that points to the good object and put those two reference objects in each `referenced` collections.

**Comment by filippomc** [comment]
Hi @aranega, thanks for the explanation!
