### ISSUE TITLE
Pyecore does not work with new Ordered_set version

### ISSUE THREAD

**Issue by fgro93** [pyecore/pyecore#87]
Ordered-set released a new version on 29th of April, which does not include `is_iterable`
https://pypi.org/project/ordered-set/

`Module 'ordered_set' hast no attribute 'is_itreable'`

Here: ordered_set_patch.py

**Comment by aranega** [comment]
Outch, thanks for the info! I'm on it, if the code moved a lot, I'll see to perhaps update my patch also.

**Comment by aranega** [comment]
@fgro93 I released a new version, which deals with the new version of `ordered_set` tell me if it works for you!

**Comment by fgro93** [comment]
@aranega Thanks for the quick fix. Seems to work fine.
