### ISSUE TITLE
Invalidating the Resource fragment's cache

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#92]
Hi @aranega,

I'm quite extensively using fragments to navigate through a model. A `Resource` caches earlier found fragments to speed up this process of fragment resolving.  E.g. from `resource.py`:
```python
 def resolve(self, fragment, resource=None):
        fragment = self.normalize(fragment)
        if fragment in self._resolve_mem:
            return self._resolve_mem[fragment]
```

The issue now is that I make changes to the model, but the cache entries are not invalidated. 
My use case is a list that is reversed, but the fragments point to the wrong index in the list:

```python
r = Resource()
line = esdl.Line()
r.append(line)
point1 = esdl.Point(lat=1.0, lon=1.0)
point2 = esdl.Point(lat=2.0, lon=2.0)
line.point.extend((point1, point2))

print('original -',line.point)
print('original - uri for point[0]', line.point[0].eURIFragment())
print('original - resolved object for', line.point[0].eURIFragment(), "(should be 1.0):", r.resolve(line.point[0].eURIFragment()))
print('fragment cache:', r._resolve_mem)
print()
print('reversing list')
rev = list(reversed(line.point))
line.point.clear()
line.point.extend(rev)
print()
print('reversed -',line.point)
print('reversed - uri for point[0]', line.point[0].eURIFragment())
resolved_point = r.resolve(line.point[0].eURIFragment())
print('reversed - resolved object for', line.point[0].eURIFragment(), '(should be 2.0):', resolved_point)
print('reversed - resolved uri fragment', resolved_point.eURIFragment())
print('fragment cache:', r._resolve_mem)
```
Output:
```
original - EOrderedSet([Point(lat=1.0), Point(lat=2.0)])
original - uri for point[0] //@point.0
original - resolved object for //@point.0 (should be 1.0): Point(lat=1.0)
fragment cache: {'//@point.0': Point(lat=1.0)}

reversing list

reversed - EOrderedSet([Point(lat=2.0), Point(lat=1.0)])
reversed - uri for point[0] //@point.0
reversed - resolved object for //@point.0 (should be 2.0): Point(lat=1.0)
reversed - resolved uri fragment //@point.1
fragment cache: {'//@point.0': Point(lat=1.0)}
```

I'm not sure what the best way is to invalidate this fragment cache. Methods such as delete, clear, insert, update, extend all need to invalidate the fragment cache of its resource.

**Comment by aranega** [comment]
Hi @ewoudwerkman 

Outch, good call! That's a edge case I didn't think about. Thanks a lot for the issue, I will try to fix that asap. This cache was especially here to be able to speed up the deserialization process, not so much during modifications of the model. So, there is two solutions:

* invalidate the cache on some operation as your suggested (could have a small impact on performances) on `delete|clear|insert` (`update|extend` shouldn't be necessary as it will only append values in the collection)
* invalidate the cache after a resource is loading and disabling the cache and let the users deal with a cache process so they can invalidate the cache at the better moment.

I have a hard time knowing what is the best solution, I will think about it (all ideas are welcome :D)

**Comment by ewoudwerkman** [comment]
I have no clue how expensive calculating a fragmentURI is. In my use case, calculating the fragmentURI is done when a user requests an object from the resource. So a few msecs is not important here as it is part of a REST call. 
I can imagine that adding cache invalidation to some operations like insert and delete, and then doing inserts & deletes a million times (e.g. when batch processing), you will notice the delay.

So I would go for option 2 I think.

**Comment by aranega** [comment]
So, I had a little bit of time today and I implemented the second version (the cache is disabled after the resource is loaded), this is not the best way of doing that, but at least, it will avoid to clear cache at each actions. I tried a version with a special listener on the resource that cleans the cache at each modification of the resource, but I don't think it will be so good for the perfs. At the moment, it is just disabled with a special attribute `cache_enabled` on the resource. If you want the cache back you can juste enable it by setting this attribute to `True`.
