### ISSUE TITLE
xsi:type tag processing question

### ISSUE THREAD

**Issue by aacebedo** [pyecore/pyecore#93]
Got myself in a special situation:

I've got a model with the following declaration:

<mytag xsi:type="atypeA">

In the metamodel: "mytag" is a eStructuralFeatures with eType to be "aTypeB", 'aTypeB' being abstract.

When I load the model, pyecore processes a 'mytag' instance and tries to instantiate an object of 'aTypeB' (which is abstract) instead of 'aTypeA', resulting in a crash as it cannot instantiate an abstract class.
Is there a way to make pyecore to process the xsi:type attribute instead of the type of the tag itself when instantiating the model ?

**Comment by aacebedo** [comment]
Ok guess I've found something:

The prefix for xsitypes in not correct.
in the XMIResource object self.xsitype is"'{http://www.omg.org/XMI}type'"
but in its self.prefixes the xsi keys contains ''http://www.w3.org/2001/XMLSchema-instance'

The mismatch provokes an issue when getting the types specified in the xsi:types attribute of the tag.

Don't know what is the source of this behaviour yet

**Comment by aranega** [comment]
I'm really sorry about all the problem you have using PyEcore at the moment, I hope that with your tickets I will reach a version more stable quickly.

Regarding your issue, you cut me short, I was going to say that the `xsi:type` has priority over the type of the structural feature. What happens is that if the XMI resource cannot find in your ecore `xsi` register as `http://www.w3.org/2001/XMLSchema-instance`, it automatically switches to `xmi:type` instead of `xsi:type`. It would mean that `xsi` is register on top of your ecore under a different url? Could you send me just your `.ecore` top definition pruned of all sensitive information?

**Comment by aacebedo** [comment]
No problem, you did an awesome work on this library ! I'm happy to be able to contribute a little.

I tried to change the ecore by putting xmi:types instead of xsi:types but didn't work. In any case I cannot change the ecore.

I solved the issue by replacing the this in xmi.py:
```
    def _type_attribute(self, node):
        type_ = node.get(self.xsitype)
        if type_ is None:
            xsi_type_url = '{{{0}}}type'.format(self.prefixes.get(XSI))
            type_ = node.get(xsi_type_url)
            if type_ is None:
                xmi_type_url = '{{{0}}}type'.format(self.prefixes.get(XMI))
                type_ = node.get(xmi_type_url)
                if type_ is not None:
                    self.xsitype = xmi_type_url
        return type_
```
In fact I try to search with the xsi_type_url in the prefix. I think it shall be the case as we already search the xmi with the prefix.

What do you think about this solution ?

**Comment by aranega** [comment]
Regarding the way the switch is implemented:

```python
def _type_attribute(self, node):
        type_ = node.get(self.xsitype)
        if type_ is None:
            xmi_type_url = '{{{0}}}type'.format(self.prefixes.get(XMI))
            type_ = node.get(xmi_type_url)
            if type_ is not None:
                self.xsitype = xmi_type_url
        return type_
```

It would suggest that your `.ecore` mixes `xmi:type` and `xsi:type`, would it be the case? If that the case, I wasn't aware it was a common practice

**Comment by aacebedo** [comment]
Yes it mixes xsi and xmi. I don't know exactly why as I am not an EMF specialist and not the author.

**Comment by aranega** [comment]
> In fact I try to search with the xsi_type_url in the prefix. I think it shall be the case as we already search the xmi with the prefix.
> 
> What do you think about this solution ?

That's a viable solution, a simpler one would be to simply get rid of the last assignation and to enable check everytimes (basically what you are doing with your solution. The code would become:

```python
def _type_attribute(self, node):
        type_ = node.get(self.xsitype)
        if type_ is None:
            xmi_type_url = '{{{0}}}type'.format(self.prefixes.get(XMI))
            type_ = node.get(xmi_type_url)
        return type_
```

I can fix and push quickly, but as you found the bug, would you like to propose a PR? I can add the related test case.

**Comment by aacebedo** [comment]
I am not sure that the solution will work as in my case the content of self.xsitype is not correct. 
The correct attribute name is obtained only with :
` xsi_type_url = '{{{0}}}type'.format(self.prefixes.get(XSI))`
I don't know why the value of self.xsitype is incorrect.

I can do the PR when we are ok for the right solution.

**Comment by aranega** [comment]
Actually, with the current algo, the content of `self.xsitype` switches at the moment it finds a `xmi:type`. With the modification I propose, the switch is not performed in a persistent way. When a `xsi:type` is not found, it will only try with `xmi:type`, but will not update `self.xsitype`. Consequently, if the second time it encounters a `xsi:type` it will try it anyway as `self.xsitype` will still be set as `xsi:type` (exactly `{http://www.w3.org/2001/XMLSchema-instance}type`). So, it should work :)

**Comment by aranega** [comment]
The fix for this issue is now included in the new version!
