### ISSUE TITLE
EShortObject is missing in ECore types

### ISSUE THREAD

**Issue by aacebedo** [pyecore/pyecore#94]
In file ecore.py all basic ECore types are declared, however I think the EShortObject is missing.

**Comment by aranega** [comment]
:sweat_smile: Good catch! Thanks, I add it directly and I push on `develop`. Sorry for the problems and really, thank you for your help!

**Comment by aacebedo** [comment]
I am doing the PR :)

**Comment by aranega** [comment]
Ah, shit, I pushed already... sorry :sweat_smile:, please propose your PR anyway, I will integrate it.

**Comment by aacebedo** [comment]
done but I there is now a conflict so I am not sure you'll be able to merge it :s

**Comment by aranega** [comment]
It's merged ;) It was my fault, I had pending commit I forgot to push.

**Comment by aranega** [comment]
Hi @aacebedo,

I finally had time to make a proper release including your PR ;)

Thanks again!
