### ISSUE TITLE
[question] How to dispatch on dynamic types of a model

### ISSUE THREAD

**Issue by aacebedo** [pyecore/pyecore#97]
Hi
I was wondering how to use the utils.dispatch class with a dynamically loaded metamodel.
I have an ecore metamodel with no pythonic representation.
I load the MM with pyecore resulting in a bunch of runtime classes "pyecore.ecore.MyClass".
I would like to write a dispatcher on the pyecore.ecore.MyClass but I do not have access to the class itself (as it is dynamically loaded by pyecore) when I write the decorator, so I cannot put the type in the register directive.

Do you have an idea of how I should proceed ?

Regards.

**Comment by aranega** [comment]
Hi @aacebedo ,sorry for the late answer. Actually, the `dispatch` decorator works with static and dynamic classes. You can pass either the instance of an `EClass` as attribute or a python class, both work in a transparent way. 

Also, you can always access the related python class from a `Eclass` instance through the `python_class` attribute :)
