### ISSUE TITLE
[bug]: Clearing an EList

### ISSUE THREAD

**Issue by ewoudwerkman** [pyecore/pyecore#99]
Hi @aranega 

As discussed in the [`pyecoregen` pull request](https://github.com/pyecore/pyecoregen/pull/24), I have a list of EDoubles in my metamodel with `unique=false`. This maps to an EList in pyecore. However, when I try to clear that list, it does not remove everything.
The bug is in the ECollection class:
```python
    def clear(self):
        for x in set(self):
            self.remove(x)
```

As you see, it puts all the list items it wants to remove in a set first, consequently only removing the unique items, instead of everything.

My proposal is to remove the `set()` in the clear operation, but I don't know what side effects are there for other ECollection classes? Do I need to wrap `self` in a `list()`?

Kind regards,
Ewoud

**Comment by aranega** [comment]
Hi @ewoudwerkman ,

Thanks so much for the issue, indeed, that was a dumb code that I wrote... I really think that changing the `set` for a `list` will not be a problem and should not induce problems. Without, I'm not so sure about the potential side-effects. I will quickly make some experiments, the tests should catch problematic code anyway (I hope)

**Comment by ewoudwerkman** [comment]
Thanks for your quick reply! I experimented a little and I found out that it needs to be wrapped in a `list`. But I don't know exactly why? It might be needed because you remove  elements from `self`, but you are also iterating over `self`.

**Comment by aranega** [comment]
Yes, that's exactly what happens, this is the classical "removing elements from a list I'm iterating over", it always has weird side effects if a copy is not done.

**Comment by ewoudwerkman** [comment]
Just as a side note: if the ECollection is large, copying all data to a new list, might impact performance. In Java you'd use an iterator to delete the items in the list one-by-one with `iterator.remove()`. In python this might work:
```python
while self:
   self.remove(self.pop())
```
But I'm always a bit reluctant to use while statements (that cause infinite loops...)

**Comment by aranega** [comment]
Sorry for the delay @ewoudwerkman, I was caught in the hell of adapting classes for remote teaching.

You're right, it could have an impact. Your solution sounds really good. It's only strange to remove the object you just pop. I understand you kept it so the notification system is still sorking. I will see if I can reify the `pop` function to directly do that.

**Comment by ewoudwerkman** [comment]
Good catch: I did not check what `pop` was doing (e.g. also making sure that the container and the opposite is updated accordingly). And `pop` is already sending the right notifications. 
I was doing it twice...

No rush! 
Thanks!
Ewoud

**Comment by aranega** [comment]
The fix is now part of master and of the new release ;) Thanks for your help and sorry for the delay...
